Dockerfile.assisted-installer-build
Jenkinsfile

tested push, can inspect here :
http://10.46.10.2:8080/job/assisted-installer/job/osher%252Ftest/15/

Added Jenkinsfile

---

src/k8s_client/k8s_client.go
src/k8s_client/mock_k8s_client.go
src/main/assisted-installer-controller/assisted_installer_main.go

Signed-off-by: Moti Asayag <masayag@redhat.com>

Rename SetEnvVars to SetProxyEnvVars

---

deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template
go.sum
src/ops/ops.go

Add CA Cert to ignition file to be added to the host
Mount CA Cert host file as volume to the controller job

MGMT-1891 Configure CA certificate path for assisted controller

---

deploy/assisted-installer-controller/assisted-installer-controller-role.yaml
go.mod
src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go
src/k8s_client/k8s_client.go
src/k8s_client/mock_k8s_client.go
src/utils/utils.go

refactoring controller code and adding 2 hours timeout for post installed operations

OCPBUGSM-18103 waiting for cluster version to be available

---

src/main/assisted-installer-controller/assisted_installer_main.go
src/utils/utils.go

Signed-off-by: Moti Asayag <masayag@redhat.com>

Move proxy-func to utils

---

Makefile

This copies the way the dev scripts handle docker/podman

Don't assume docker in the makefile

---

OWNERS
OWNERS_ALIASES

NO-ISSUE Update owner file

---

go.mod
src/installer/installer_test.go

In response to https://github.com/openshift/assisted-installer/pull/78#discussion_r522160320

NO-ISSUE Add installer args to test cases

---

src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go
src/common/common.go
src/main/assisted-installer-controller-ocp/main.go
src/main/assisted-installer-controller/assisted_installer_main.go

* Part 2 of add must gather logs
* Add indication when all the hosts are in error state ([MGMT-2711](https://issues.redhat.com/browse/MGMT-2711))

MGMT-2403 Add status flag to the post-reboot processes

---

Dockerfile.assisted-installer-controller
Makefile

* Add oc adm client to controller image
* oc requires change in base image to run (dep on glibc)

MGMT-2403 Add oc to controller's image

---

src/ops/ops.go

MGMT-2779 Add --net=host to log sender command to enable it to communicate on top of IPv6

---

Dockerfile.assisted-installer
Dockerfile.assisted-installer-build
Dockerfile.assisted-installer-controller-ocp

To avoid docker hub limitations

Use quay.io/app-sre/golang for build container

---

src/installer/installer.go

NO-ISSUE: Adding the error to logs when extracting ignition to disk.

---

src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go

To be followed up with a proper config flag.

MGMT-3063 Add Env variable to enable/disable CVO wait 

---

src/installer/installer.go
src/installer/installer_test.go
src/k8s_client/k8s_client.go
src/k8s_client/mock_k8s_client.go

- This fixes it for IPv6 single node

MGMT-3519 Change control plane replicas patch to do the patch only when control plane replicas is 3

---

Makefile

See https://github.com/openshift/release/pull/14728

NO-ISSUE: Updates to simplify openshift/release jobs

---

src/installer/installer.go

NO-ISSUE: Adding the error itself to the logs message.

---

Dockerfile.assisted-installer
Dockerfile.assisted-installer-controller
Dockerfile.assisted-installer-controller-ocp
Makefile

See https://github.com/openshift/release/pull/14728

NO-ISSUE: Work to get images built in prow

---

Jenkinsfile

Resolves https://github.com/openshift/assisted-installer/pull/169 issue with Jenkinsfile

NO-ISSUE Add openshift CI credentials to Jenkins

---

src/assisted_installer_controller/assisted_installer_controller.go

`time="2021-01-18T10:14:43Z" level=info msg="Host status: map[test-infra-cluster-assisted-installer-master-0:installing-in-progress test-infra-cluster-assisted-installer-master-1:installing-in-progress test-infra-cluster-assisted-installer-master-2:installing-in-progress]" request_id=edce54f5-02a3-4720-bcfd-d3703390420d`

MGMT-2485 Add hosts and status from service to log

---

src/installer/installer.go
src/installer/installer_test.go
src/utils/utils.go

/cc @eranco74 
/cc @tsorya 
/cc @romfreiman

MGMT-3397 Do not apply 3->2->3 patch from Openshift 4.7 and later

---

src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go
src/k8s_client/k8s_client.go
src/k8s_client/mock_k8s_client.go

certificates.k8s.io/v1 in assisted-controller, it will remove many
warnings in the logs

MGMT-3860 Change use of certificates.k8s.io/v1beta1 to

---

src/assisted_installer_controller/assisted_installer_controller.go

NO-ISSUE fix typo of the word 'available'

---

src/ops/ops.go

Overcome https://github.com/coreos/coreos-installer/issues/512 bug.
coreos-installer has a bug where when a disk has busy partitions, it will
print a confusing error message if that disk doesn't have a `/dev/*` style path.
The service may give us paths that don't have the `/dev/*` path format but instead
are symlinks to the actual `/dev/*` path. e.g. `/dev/disk/by-id/wwn-*`.
To fix the bug we simply resolve the symlink and pass the resolved link to coreos-installer.

MGMT-4865 - Resolve installation disk symlink before running coreos-installer

---

deploy/assisted-installer-controller/assisted-installer-controller-role.yaml
src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go
src/k8s_client/k8s_client.go
src/k8s_client/mock_k8s_client.go
src/main/assisted-installer-controller/assisted_installer_main.go
src/utils/utils.go

Kill any service that take the .10 IP address in service network
so that the DNS service can take it.

OCPBUGSM-26978 Hack to release .10 DNS IP

---

go.sum
src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go
src/utils/utils.go

Reopen https://github.com/openshift/assisted-installer/pull/210
/cc @eranco74 @tsorya

MGMT-3145 Reset CVO timeout in case of a change

---

OWNERS_ALIASES

NO-ISSUE Add flaper87 to the code-reviewers

---

OWNERS
OWNERS_ALIASES

NO-ISSUE: Update ocm-2.3 branch with limited approvers

---

OWNERS
OWNERS_ALIASES

Fixing some confusion I have with OWNERS files definition.
/cc @ronniel1 @romfreiman @YuviGold 
/hold

fix OWNERS files to match group members roles

---

src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go

MGMT-7201: Wrap PostInstallConfigs logs and pass the entire failure message to the service

---

src/ops/ops.go

- Minor change to log regarding boot order setup on BIOS systems
/cc @osherdp

Bug 1979009: Change log message about EFI support

---

src/installer/installer.go

NO-ISSUE: Log message before uploading logs to service

---

src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go

Fix for very specific case when cvo has new messages all the time but in
reality it is stuck.
Adding CVOMaxTimeout with 3 hours that will cause waitForPredicate to exit even though timer is updated due to new cvo message

OCPBUGSM-27526: Cluster deployment freeze on Finalizing stage forever on Cluster Version Operator

---

deploy/assisted-installer-controller/assisted-installer-controller-cm.yaml.template

This will allow both string and json input to the must-gather image

MGMT-4893: quote must-gather-image env variable in controller manifest

---

src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go

We have a workaround that deletes service that took address of dns
service. Till now it supported only ipv4. This change adds ipv6 support

OCPBUGSM-32117: Adding ipv6 support to dns busy address workaround

---

src/ops/ops.go
src/ops/ops_test.go

Adding function that will change token value to <SECRET>

MGMT-7450: Removing pull secret token from failure logs

---

src/installer/installer.go
src/installer/installer_test.go

MGMT-7178: Assisted-installer should not reboot worker till min number of masters have joined

---

OWNERS_ALIASES

MGMT-7597: Remove ronniel1, razregev, and asalkeld from OWNERS

---

src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go
src/assisted_installer_controller/operator_handler.go
src/ops/mock_ops.go
src/ops/ops.go
src/utils/utils.go

Depends on: https://github.com/openshift/assisted-service/pull/2266

MGMT-7292: Wait for the OLM to be initilized before CR apply

---

src/ops/ops.go

SetBootOrder is using efibootmgr for selecting the correct device.
The specified loader should be set with an appropriate efi file according to the runtime CPU architecture.
I.e.
x86_64 -> shimx64.efi
arm64 -> shimaa64.efi

MGMT-7750: get efi file according to cpu architecture

---

src/assisted_installer_controller/assisted_installer_controller.go
src/common/common.go
src/common/common_test.go
src/installer/installer.go

This commit adds an ability to match nodes during the installation using
their IP addresses as well as reported hostnames.
Currently only the hostname of the node is taken into account and
compared against the known inventory. With this PR we are adding a
feature that, in case of a name mismatch, performs a scan over IP
addresses of the reporting node and nodes in the inventory and if the
match is found, accepts the node.
This is to cover cases where the node name in the inventory is not an
exact match with the name reported by the node itself.
Contributes-to: [MGMT-7315](https://issues.redhat.com/browse/MGMT-7315)

MGMT-7315: Support IP-based matching of nodes during installation

---

src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go

MGMT-4078: Validate console operator in parallel to CVO

---

go.mod
go.sum
src/inventory_client/inventory_client.go

There is no need to fetch operator status every couple of seconds,
that's why we are adding cache for operator status for 30 seconds

MGMT-7912: Controller: Add cache to the operators status API

---

OWNERS_ALIASES

NO-ISSUE - add eliorerz and celebdor to owners

---

go.mod
go.sum

This is a cherry-pick of https://github.com/openshift/assisted-installer/pull/431

[release-ocm-2.5] NO-ISSUE: bump assisted-service version

---

src/installer/installer.go

In case that there is a problem accessing the assisted
service, access to the service will be retried up to timeout of 60
minutes.
/cc @tsorya 
/cc @filanov

MGMT-9898: In assisted installer, add timeout and retry when worker is waiting for 2 ready masters

---

src/installer/installer.go

[MGMT-9971](https://issues.redhat.com//browse/MGMT-9971): removing timeout from waiting for 2 master.
Moving back to the logic where timeout is decision is taken only by
service

MGMT-9971: removing timeout from waiting for 2 master.

---

src/assisted_installer_controller/assisted_installer_controller.go

[MGMT-10017](https://issues.redhat.com//browse/MGMT-10017): Cluster get to Error when OLM operator failed on applying post manifests
in case any of the functions in waitForOlm fails we will set timeout for
pending olm operator

MGMT-10017: Cluster get to Error when OLM operator failed on applying post manifests

---

src/common/common.go
src/installer/installer.go
src/installer/installer_test.go
src/inventory_client/inventory_client.go
src/k8s_client/k8s_client.go
src/main/drymock/dry_mode_k8s_mock.go
src/ops/coreos_installer_log_writer.go
src/ops/ops.go
src/utils/utils.go

MGMT-10077: Use logrus.FieldLogger instead of *logrus.Logger

---

src/ops/ops.go

NO-ISSUE: Skip preparation of controller files in dry mode

---

src/assisted_installer_controller/assisted_installer_controller.go

Mainly a dummy PR to trigger image promotion to MCE 2.1.
/cc @eliorerz @tsorya

NO-ISSUE: fix typo in word 'operators'

---

src/assisted_installer_controller/assisted_installer_controller.go

MGMT-11100: changing url for router status check from console to canary

---

src/ops/ops.go

Bug 2122012: assisted-installer isn't sending the host logs in case th…e installation was successful and cacert was  added

Bug 2122012: assisted-installer isn't sending the host logs in case th…e installation was successful and cacert was  added

---

deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template

Fixes: #551
Contributes-to: [MGMT-12115](https://issues.redhat.com//browse/MGMT-12115)

MGMT-12115: Fix wrong formatting in Controller Pod definition

---

src/common/common.go

NO-ISSUE: improvement on gathering controller logs, validating that buffer is not empty

NO-ISSUE: improvement on gathering controller logs, validating that buffer is not empty

---

src/ops/ops.go

Adding more logs to help on debugging LVM cleanup issues
/cc @filanov
/cc @paul-maidment

MGMT-12984: Add more logs to LVM cleanup

---

src/installer/installer.go
src/installer/installer_test.go
src/ops/mock_ops.go
src/ops/ops.go

reboot now only when installing single node

MGMT-13385: Installation fail due to race condition in etcd bootstrap strategy

---

src/common/common.go
src/common/common_test.go
test_files/mcs_logs.txt

OCPBUGS-7149: IPv6 multinode spoke no moving from rebooting/configuring stage

---

src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/assisted_installer_controller_test.go

Reverts openshift/assisted-installer#628

Revert "MGMT-13595: Allow moving node from rebooting to joined"

---

src/assisted_installer_controller/assisted_installer_controller.go
src/assisted_installer_controller/operator_handler.go
src/common/common.go
src/utils/tarutil.go
src/utils/utils.go

NO-ISSUE: In case upload of must-gather fails we need to retry to upload
and not to gather it one more time as it has less chance to succeed
In case pod name doesn't exist add one in order to upload file
NO-ISSUE: Adding log operator status conditions

NO-ISSUE: controller logs optimizations

---

OWNERS
OWNERS_ALIASES

To keep these branches in sync with the current
roles.
/cc @carbonin

NO-ISSUE: Update OWNERS to match master branch

---

.github/dependabot.yml

* fix for failing test on PR #705

NO-ISSUE: dependabot exclude k8s

---

Dockerfile.assisted-installer
Dockerfile.assisted-installer-build
Dockerfile.assisted-installer-controller
go.mod

MGMT-16039: upgrade to golang 1.20

---

src/ops/ops.go
src/ops/ops_test.go

In 4.16 when EFI boot loader is in use, centos boot entry might be in use and RHEL.  This causes the directory structure in the second partition to contain "centos" instead of "redhat". In this commit, the modification queries the directory structure and adapts accordingly.
/cc @carbonin 
/cc @tsorya

OCPBUGS-30056: RAN - SNO 4.16 deployment - Failed at Rebooting in agent

---

src/assisted_installer_controller/assisted_installer_controller.go

Fix typo in "envconfig" field tag
/cc @gamli75 
/cc @carbonin

MGMT-17353: Debug pod left in ImagePullBackOff after install in disconnected environment

---

Dockerfile.assisted-installer
Dockerfile.assisted-installer-controller

ARM and other arch failing due to base images  not supporting the architecture

NO-ISSUE: fixing ARM images builds

---

Dockerfile.assisted-installer-controller-downstream
Dockerfile.assisted-installer-downstream

Add downstream dockerfile to upstream repo for konflux migration from cpaas.
Part-of [MGMT-19453](https://issues.redhat.com//browse/MGMT-19453)

MGMT-19453: Add downstream dockerfile

---

.tekton/assisted-installer-controller-downstream-main-pull-request.yaml
.tekton/assisted-installer-controller-downstream-main-push.yaml
.tekton/assisted-installer-controller-mce-downstream-2-13-pull-request.yaml
.tekton/assisted-installer-controller-mce-downstream-2-13-push.yaml
.tekton/assisted-installer-controller-mce-downstream-main-pull-request.yaml
.tekton/assisted-installer-controller-mce-downstream-main-push.yaml
.tekton/assisted-installer-downstream-main-pull-request.yaml
.tekton/assisted-installer-downstream-main-push.yaml
.tekton/assisted-installer-mce-downstream-2-13-pull-request.yaml
.tekton/assisted-installer-mce-downstream-2-13-push.yaml
.tekton/assisted-installer-mce-downstream-main-pull-request.yaml
.tekton/assisted-installer-mce-downstream-main-push.yaml
Dockerfile.assisted-installer-controller-downstream
Dockerfile.assisted-installer-controller-mce
Dockerfile.assisted-installer-downstream
Dockerfile.assisted-installer-mce
rpm-prefetching/README.md
rpm-prefetching/assisted-installer-controller/rpms.in.yaml
rpm-prefetching/assisted-installer-controller/rpms.lock.yaml
rpm-prefetching/assisted-installer/rpms.in.yaml
rpm-prefetching/assisted-installer/rpms.lock.yaml

Configure the following things for releasing in konflux:
- Hermetic builds
- Pushing source image.
- Adding label io.openshift.tags.
- Setting up snyk
Part-of [MGMT-19645](https://issues.redhat.com//browse/MGMT-19645)

MGMT-19645: Configure a few things for releasing in konflux

---

renovate.json

Add renovate config to limiot number of konflux PR
With that config, PR should be automerged when tests succeeded

MGMT-19734: Add renovate config to limit number of PRs

---

README.md

Reverts openshift/assisted-installer#1040

Revert "[release-ocm-2.13] NO-ISSUE: Trigger new MCE 2.8 pipeline"

---

.tekton/assisted-installer-acm-ds-2-13-pull-request.yaml
.tekton/assisted-installer-acm-ds-2-13-push.yaml
.tekton/assisted-installer-controller-acm-ds-2-13-pull-request.yaml
.tekton/assisted-installer-controller-acm-ds-2-13-push.yaml

Tasks will become mandatory the 1st of April

MGMT-20149: Add required tasks for Konflux

---

OWNERS_ALIASES

Eran has left Assisted Installer team

[release-ocm-2.13] NO-ISSUE: Remove Eran Ifrach account from OWNERS

---

OWNERS_ALIASES

Paul has left Assisted Installer team

NO-ISSUE: Remove Paul account from OWNERS

---

.tekton/assisted-installer-acm-ds-2-14-pull-request.yaml
.tekton/assisted-installer-acm-ds-2-14-push.yaml
.tekton/assisted-installer-acm-ds-main-pull-request.yaml
.tekton/assisted-installer-acm-ds-main-push.yaml
.tekton/assisted-installer-controller-acm-ds-2-14-pull-request.yaml
.tekton/assisted-installer-controller-acm-ds-2-14-push.yaml
.tekton/assisted-installer-controller-acm-ds-main-pull-request.yaml
.tekton/assisted-installer-controller-acm-ds-main-push.yaml
.tekton/assisted-installer-controller-ds-main-pull-request.yaml
.tekton/assisted-installer-controller-ds-main-push.yaml
.tekton/assisted-installer-ds-main-pull-request.yaml
.tekton/assisted-installer-ds-main-push.yaml

Tasks will become mandatory the 1st of April

MGMT-20149: Add required SAST tasks for Konflux

---

.tekton/assisted-installer-acm-ds-2-15-pull-request.yaml
.tekton/assisted-installer-acm-ds-2-15-push.yaml
.tekton/assisted-installer-controller-acm-ds-2-15-pull-request.yaml
.tekton/assisted-installer-controller-acm-ds-2-15-push.yaml

NO-ISSUE: Modify Konflux YAMLs to ocm-2.15

---

.tekton/assisted-installer-acm-ds-2-14-pull-request.yaml
.tekton/assisted-installer-acm-ds-2-14-push.yaml
.tekton/assisted-installer-controller-acm-ds-2-14-pull-request.yaml
.tekton/assisted-installer-controller-acm-ds-2-14-push.yaml

Konflux service account migration, has to be done before June 14th

NO-ISSUE: Konflux service account migration
