go.mod, go.sum, src/utils/utils.go
Replace `ori-amizur/introspector` with `openshift/assisted-installer-agent` and run `go mod tidy` to clean up unneeded dependencies.
=> Fix dependencies to point to new agent repo

Dockerfile.assisted-installer-build, src/inventory_client/retry_roundtripper.go
"/src/inventory_client/retry_roundtripper.go:23:11: cannot use rrt.delay (variable of type time.Duration) as time.Duration value in struct literal"
https://github.com/golangci/golangci-lint/issues/995
=> Fixed time.Duration lint failure

src/assisted_installer_controller/assisted_installer_controller.go, src/config/config.go, src/ops/ops.go
On D/S image, nsenter is being executed without environment variables,
therefore no proxy configuration are enabled to 'coreos-installer'
command which attempt to download a resource.
While the issue isn't happened to commands running on 'bash' image used
for U/S assisted-installer image, D/S image uses ubi8-minimal which
behaves differently and requires the env-vars to be provided explicitly
(assuming we'd like to avoid hacking the process id of the agent in
order to inherit the already-provided env-vars for proxy from it).
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1877757
Signed-off-by: Moti Asayag <masayag@redhat.com>
=> Accept proxy settings in install command

deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template, deploy/assisted-installer-controller/assisted-installer-controller-role.yaml, go.sum, src/k8s_client/k8s_client.go, src/k8s_client/mock_k8s_client.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/main/main.go, src/ops/ops.go
The assisted-installer requires to use the same proxy settings as
specified by the user.
The assisted-installer-controller runs on OCP cluster and should use the
cluster-wide proxy, based on its processed status in order to assure
in-cluster communication is unproxified.
=> OCPBUGSM-17295 Set proxy env vars for controller

go.mod, src/inventory_client/inventory_client.go, src/inventory_client/retry_roundtripper.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/main/main.go
ProxyFromEnvVars provides an alternative to http.ProxyFromEnvironment
since it is being initialized only once and that happens by k8s before
proxy settings was obtained from the cluster.
While this is no issue for k8s client, it prevents any out-of-cluster
traffic from using the proxy.
By providing implementation of that method, we allow to use env-vars
set for the pod based on the cluster-wide-proxy.
Signed-off-by: Moti Asayag <masayag@redhat.com>
=> OCPBUGSM-17295 Implement Proxy function

go.mod, go.sum, src/config/config.go, src/main/main.go
Recreated https://github.com/openshift/assisted-installer/pull/86 because it wouldn't let me reopen
Same as before, but the dump function moved to assisted-service
Had to run 
```go get github.com/openshift/assisted-service@bb2f4a5dbbd8357716edeacc0ffbc540fa1e1757```
to get the relevant version of assisted-service, I hope it's alright.
=> MGMT-2629 PullSecretToken marked secret

go.mod, src/config/config.go, src/installer/installer.go, src/installer/installer_test.go, src/ops/coreos_installer_log_writer_test.go, src/ops/mock_ops.go, src/ops/ops.go, src/ops/ops_suite_test.go, src/ops/ops_test.go
This allows for customizing things like kernel args as well as bringing networking files forward from the previous stage.
[MGMT-2694](https://issues.redhat.com/browse/MGMT-2694)
=> MGMT-2694 Add additional args to coreos-installer command

src/config/config.go
This is not used as of 93495e81245278863102d155b15b4d0782641ff4 and is no longer being sent from the service as of openshift/assisted-service#670
=> MGMT-2634 Remove host-name flag

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/common/common.go, src/common/common_test.go, src/installer/installer.go, src/installer/installer_test.go, src/inventory_client/inventory_client.go, src/inventory_client/inventory_client_test.go, src/inventory_client/mock_inventory_client.go, src/ops/coreos_installer_log_writer.go, src/ops/coreos_installer_log_writer_test.go, src/utils/utils.go
In order to be ease the debug process of requests and responses
sent from assisted-installer to assisted-service and backwards a
request id will be added to each request. Loggers will print any
errors returned from assisted-service with this request id (same
as it works in assisted-installer-agent).
=> MGMT-2409: Added request id to each InventoryClient request

go.mod, go.sum, src/installer/installer.go, src/installer/installer_test.go, src/installer/ssh_consts.go, src/ops/mock_ops.go, src/ops/ops.go
It will allows bootstrap SSH to masters in order to collect
`installer-gather.sh` logs in case of cluster installation failure.
=> MGMT-2678: Adding bootstrap public SSH key to masters ignition.

Makefile
Makefile: added 'image_controller_ocp' target to 'all' target.
=> MGMT-2465: added image_controller_ocp to all target

go.mod, go.sum, src/installer/installer.go, src/installer/installer_test.go, src/installer/ssh_consts.go, src/ops/mock_ops.go, src/ops/ops.go
It will allows bootstrap SSH to masters in order to collect
`installer-gather.sh` logs in case of cluster installation failure.
=> MGMT-2678: Adding bootstrap public SSH key to masters ignition. (#80)

go.mod, go.sum, src/inventory_client/inventory_client.go
Currently due to a bug in assisted-service API, the Error() function
prints memory addresses instead of values.
Fixing the bug in assisted-service side will break backward
compatibility, therefore the fix should be made here.
Before logging the error, try to convert it to one of assisted
service Error or InfraError errors, and build the message from
the payload.
See an example of the bad error format:
Oct 09 04:43:36 localhost installer[182675]: time="2020-10-09T04:43:36Z" level=error msg="Failed to fetch file (worker.ign) from server. err: [GET /clusters/{cluster_id}/downloads/files][409] downloadClusterFilesConflict &{Code:0xc00038aa70 Href:0xc00038aa80 ID:0xc000541e04 Kind:0xc00038aa90 Reason:0xc00038aaa0}"
Oct 09 04:43:36 localhost installer[182675]: time="2020-10-09T04:43:36Z" …
=> MGMT-2411: fixed bad error format log

src/installer/installer.go
Nothing should be done before changing state to REBOOT and actual
reboot.
This is causing timing issues on logs collection that may take few
seconds/minutes to finish.
=> NO-ISSUE: Uploading logs before changing state to REBOOT.

README.md, deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template, go.mod, go.sum, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/installer/installer.go, src/installer/installer_test.go, src/ops/ops.go, src/utils/utils.go, src/utils/utils_test.go
Going forward we will use a marker file written to the bootstrap
node. This is implemented in the service in  openshift/assisted-service#672
and the etcd operator in openshift/cluster-etcd-operator#449
We also need to consider what version of openshift will contain the
etcd operator enhancement we require before merging this.
Fixes [MGMT-2454](https://issues.redhat.com/browse/MGMT-2454)
Alternative to https://github.com/openshift/assisted-installer/pull/47
=> MGMT-2454 Remove patch for unsupported etcd flag for versions >= 4.7

src/installer/installer.go, src/installer/installer_test.go
Combination of ``--pid=host`` and ``--privilege`` should be enough for it to work
=> MGMT-3298: enable MCD to use 'systemd start rpm-ostreed' while running as a container

src/ops/ops.go
Fix logs-sender command when run from installer and align it with the command
as recieved from assisted-service and executed by the next-step-runner
=> MGMT-3256 pvdisplay fails to run

go.mod, go.sum, src/installer/installer.go, src/installer/installer_test.go, src/k8s_client/k8s_client.go, src/k8s_client/mock_k8s_client.go
This change id for OVNKubernetes network type only
When starting network with OVNKubernetes netwkork type, the operator requires
that all replicas of controlPlane, which are actually the masters, will be up.
Since one of the Assisted Installer masters is actually the bootstrap when the network is started,
this network type cannot be started.
This patch changes temporarily the number of replicas to 2, to let the network start,
and then returns it to 3.
/cc @eranco74 
/cc @tsorya
=> MGMT-3179 OVNKubernetes Patch for IPv6

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/common/common.go, src/main/assisted-installer-controller/assisted_installer_main.go
Report back if oc-must gater command has failed and retry
for an hour to fetch the logs before aborting completely
This will give an opportunity for the newly formed cluster
to stabilize and evetually serve the gather pod
=> MGMT-2403 retry mechanism for oc must-gather logs

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/k8s_client/k8s_client.go, src/k8s_client/mock_k8s_client.go
In the current situation (no provisioning resource)
- don't change anything
In the new situation of having a provisioning resource
- set host.Spec.ExternallyProvisioned=true
- don't move the metal3v1alpha1.StatusAnnotation
- remove the metal3v1alpha1.PausedAnnotation (set on masters by the installer)
- continue setting the controllerRef
Provisioning is enabled by https://github.com/openshift/assisted-service/pull/709 when we have 4.7 and above.
This can be merged now as it is only used when the PR above is merged.
=> MGMT-2662 Handle the case when MetalProvisioning exists

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/k8s_client/k8s_client.go, src/k8s_client/mock_k8s_client.go, src/utils/tarutil_test.go
In order to verify the availability of the console operator, the assisted
controller needs to monitor the console operator availability.
```
time="2021-02-15T23:51:34Z" level=info msg="Checking if console is available"
time="2021-02-15T23:51:34Z" level=warning msg="Operator console condition 'Available' is not met due to 'Deployment_FailedUpdate': DeploymentAvailable: 2 replicas ready at version 4.6.16"
time="2021-02-15T23:52:03Z" level=info msg="Start uploading controller logs (intermediate snapshot)"
time="2021-02-15T23:52:03Z" level=info msg="Uploading logs for assisted-installer-controller-g5vcx in assisted-installer"
W0215 23:52:03.346958       1 warnings.go:67] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use …
```
=> MGMT-4078 Monitor console operator

src/installer/installer_test.go
This extends the unit tests run for the AI installer to verify that both
minor and pre release versions are managed. Just one more unit test
=> MGMT-4185 Add other minor and pre versions to tests

deploy/assisted-installer-controller/assisted-installer-controller-cm.yaml.template, deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/config/config.go, src/ops/mock_ops.go, src/ops/ops.go
Tell must-gather command which image to use. This should enable
to run must-gather with an available and working image instead of
the default latest in cases when it's not possible to get an image
ID from OCP stream (e.g. the API fails).
=> MGMT-4479 Specify must-gather image

src/ops/ops.go
This function get called in loops while waiting for marker files, logging every command that failed sapm the log
When the command output matters the caller pass liveLogger, in such case it should log the detailed command error
=> MGMT-4839 Reduce spam logs from ops.ExecCommand

go.sum, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/common/common.go, src/common/common_test.go, src/installer/installer.go
The controller doesn't inform in case there's an unknown hostname
in the k8s nodes. It will just get a timeout for not finding the wanted hosts.
In addition, the bootstrap does inform about it (warning logs) while it should fail.
=> MGMT-4836 Enhance unknown host logs

go.sum, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go
This PR add a functionality to update the pending operators in case of
timeout. Previously we left the OLM operators state as it was. So in
case timeout occur the operators which didn't finished had state
progressing. With this PR we update the state of the operators, which
timed out to Failed state. So the assisted-service can switch the state
to completed.
=> OCPBUGSM-27183: Update pending OLM operators in case of timeout

go.sum, src/ops/coreos_installer_log_writer.go, src/ops/coreos_installer_log_writer_test.go
Report progress if the progress percentage is 100 regardless of the progress delta
Make sure we don't spam and only report it once by verifying that the lastProgress isn't 100%
=> OCPBUGSM-27324 Some hosts may never publish "Writing image to disk: 100%" event

go.sum, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/inventory_client/inventory_client.go, src/inventory_client/mock_inventory_client.go, src/k8s_client/mock_k8s_client.go, src/utils/utils.go
Without the sync, a network issue could occur and an operator update could be
missed. Hence, it is mandatory to verify that the service is aligned
with the operators' statuses before existing.
In addition, a lot of organization in the assisted_installer_controller
UTs.
The OLM implementation already takes care of going over the progressing
monitored operator.
/cc @nmagnezi @tsorya
=> OCPBUGSM-27526 Sync operator status with the service

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/inventory_client/inventory_client.go, src/inventory_client/mock_inventory_client.go
CVO is being monitored using the generic cluster monitored operators
API. There's no need for the cluster progress field anymore.
All the relevant code was deleted.
/cc @nmagnezi 
Matches https://github.com/openshift/assisted-service/pull/1509
=> MGMT-5188 Deprecate UpdateClusterInstallProgress API

go.mod, go.sum, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/inventory_client/inventory_client.go, src/main/assisted-installer-controller-ocp/main.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/main/assisted-installer-controller/assisted_installer_main_test.go, src/utils/utils.go
MGMT-[OCPBUGSM-27367](https://issues.redhat.com/browse/OCPBUGSM-27367) Reset cluster mentioned 5/6 installation logs were collected  but when downloading there are 6
Controller will have monitoring loop that will monitor connection to
service. If cluster will be cancelled or installer monitor will not set
error and exit. On cluster error monitor will set error that will say to
upload logs to upload must gather.
If 10 401/404 errors will occured in a row, it will exit 0
=> MGMT-4992 - stop controller after 10 errors of 401/404.

src/ops/ops.go
The EFI partition is not necesarily ready to be mounted right after coreos-installer is called. There
is a race which causes the SetBootOrder call to fail.
This commit removes the mount step as it doens't seem to be really needed for the efibootmgr call. This commit
once tested in one of the faulty environments where the issue could be replicated constantly and it resulted
in the expected behavior. Boot order is set correctly and node starts
/cc @eranco74 git-blame says you added this code https://github.com/openshift/assisted-installer/commit/9c5698f078e07fd4d00b1f982228c0e600279640 Would love your review here :) 
=> MGMT-6283 Remove EFI partition mount

src/main/assisted-installer-controller/assisted_installer_main.go, src/main/assisted-installer-controller/assisted_installer_main_test.go
In case of 404 controller will exit immediately(up to one minute) in case of 401 controller will exit after 3 minutes
=> OCPBUGSM-29397 decrease waiting time in case of cluster was not found or not authorized

go.mod, go.sum, src/installer/installer.go, src/installer/installer_test.go
When the bootstrap node host status is "waiting for control plane" it's actually waiting for multiple different things:
1. Wait for a minimal number of ready master nodes
2. Wait for bootkube to finish
3. Wait for the controller to be ready
After this change the assisted-service will reflect the above stages in the host progress
=> MGMT-6584 Add host progress stages while waiting for control plane

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/ops/mock_ops.go, src/ops/ops.go
This PR add a possibility to create manifests from assisted-installer.
In some cases it may be useful to create manifest from
assisted-isntaller instead of openshift-installer. For example when
installing CNV/LSO/OCS we need to have predefined CRDs for the
operators, because at the time of the operator is being created the CRDs
are not yet created by the OLM.
This PR add support to read the files from `custom_manifests.yaml` which is retrieved
from the assisted-service. The manifest are created via `oc create -f` command,
using the `kubeconfig-noingress` file.
=> MGMT-4668: Add support to create manifest in assisted-installer

Jenkinsfile
Fixes a small bug where the wrong format date string was used. 😅 
I've been using the Jenkins replay functionality to test Jenkins changes:
Here is the manual replay log:
http://assisted-jenkins.usersys.redhat.com/job/assisted-service/job/ocm-2.3/36/console
First one is YMMdd (new), second is Ymd (current) third is H for the current hour.
Signed-off-by: Lisa Rashidi-Ranjbar <lranjbar@redhat.com>
=> NO-ISSUE: Fix bug in the date for ocm image

deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template, src/main/assisted-installer-controller/assisted_installer_main.go
In case it takes long time fopr dns operator to start we can get timeout
in assisted-service cause assisted-controller can't reach the service.
Another issue is that we are workarounding dns pod issue in
assisted-controller and that's why this part should run before
controller tries to reach the service.
From now controller will use host network and will not be dependent on
dns pod.
=> OCPBUGSM-30942: ACM/ZTP with Wan emulation, SNO cluster installs do not show as installed although they are

deploy/assisted-installer-controller/assisted-installer-controller-role.yaml, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/k8s_client/k8s_client.go, src/k8s_client/mock_k8s_client.go
Currently the `assisted-installer` namespace on the cluster installed
using Assisted Installer is labeled with run-level what causes any
workload running there to bypass security constrains. In a scenario when
an operator tries to reuse this namespace to deploy Assisted Service on
such a cluster, the installation will fail because services expect to be
run using the safe UID/GID ranges.
In order to overcome the issue, after the installation of the
cluster we will remove the label from the `assisted-installer` namespace
so that if an operator wants to deploy Assisted Service, it will be
necessary to recreate the namespace (this time without setting a run-level).
Please note that if for any reason removing the label fails, we will not
fail the installation of the cluster.
Long-term solution …
=> Bug 1951812: Remove label from AI namespace after cluster installation

src/ops/ops.go
Refering to shim as BOOTX64.EFI triggers a bug
we'd like to avoid.
=> Bug 1973314: Update the uefi boot entry use shimx64

src/assisted_installer_controller/assisted_installer_controller.go
The following build error was introduced when #311 was merged
```
04:30:32  INFO [runner] linters took 31.854032639s with stages: goanalysis_metalinter: 24.07037174s, unused: 7.779939059s 
04:30:32  src/assisted_installer_controller/assisted_installer_controller.go:460:5: shadow: declaration of "err" shadows declaration at line 453 (govet)
04:30:32  	if err := c.ic.DownloadFile(ctx, customManifestsFile, customManifestPath); err != nil {
04:30:32  	   ^
04:30:32  INFO File cache stats: 1 entries of total size 37.7KiB 
04:30:32  INFO Memory: 318 samples, avg is 771.2MB, max is 1485.3MB 
04:30:32  INFO Execution took 36.471920287s       
```
Signed-off-by: Lisa Rashidi-Ranjbar <lranjbar@redhat.com>
=> NO-ISSUE Fix build error created when PR #311 merged

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/utils/utils.go
This commit add a retry mechanism while waiting for the operator to be
ready. If we apply the CR of the operator it may happen (bug 1968606),
that the OLM will report the Failed state, even that it's actually
progressing. So we decided to ignore the failed state for few times.
=> OCPBUGSM-30066: Retry wait for operator in case it failed

src/ops/ops.go
- Minor log changes on `setting EFI boot order unsupported`
- In `SetBootOrder` function - passing `liveLogger=nil` in order to not have an uneeded log at that stage
(Failed executing nsenter...)
=> Bug 1979009: Change log message about EFI support

Dockerfile.assisted-installer, Dockerfile.assisted-installer-build, Dockerfile.assisted-installer-controller, go.mod
older versions of go are out of support, so for security compliance, we were trying to get all components on the latest version. 1.14 is already out of support, i.e. https://endoflife.date/go
=> MGMT-7210 Upgrade Go version to 1.16

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/assisted_installer_controller/operator_handler.go
Switch to a a generic `isOperatorAvailable` function that would be used
for getting any class that inherits `OperatorHandler`.
This function gets the operator status from the service, if the status
is available - stop running. Otherwise, get the operator status
locally and check if it is different than the status at the service, if
so - send an update to the service.
There are 3 implementations for the OperatorHandler` interface:
- ClusterOperatorHandler (such as console)
- ClusterVersionHandler (only CVO)
- ClusterServiceVersionHandler (such as OCS, LSO)
/cc @machacekondra  @eranco74 @tsorya
=> MGMT-7149: Merge wait for operators

src/assisted_installer_controller/assisted_installer_controller.go
The method call getProgressingOLMOperators could return error in case
the assisted service API is unavailable. In that case we wouldn't update
the status of the operators which are pending and it may happend that
the cluster will hang in finalizing state.
=> OCPBUGSM-31942: Return error on failed status operator update

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/assisted_installer_controller/operator_handler.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/main/assisted-installer-controller/assisted_installer_main_test.go, src/ops/mock_ops.go, src/ops/ops.go
- Add support for JSON-formatted MUST_GATHER_IMAGE variable
- Backward compatability with other formats of MUST_GATHER_IMAGE
- When one of the Olm operator fails or timesout it is marked on the controller status
- At the end of the installation process (either normal or aborted) we check if must-gather
report should be collected and with what scope
=> MGMT-4893: Add Must-Gather reports when olm controllers fail

src/assisted_installer_controller/assisted_installer_controller_test.go, src/common/common.go
Right now in case we kube-api-server is not reachable we will not send
any logs. This code is changing, from now in case kube-api error we will
send this error as log
=> MGMT-3817: assisted-controller should always send logs

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go
joined status to the cluster.
Now they will send joined and only then done
=> OCPBUGSM-31802: hosts that were moved to ready state in k8s, didn't send

src/config/config.go, src/installer/installer.go, src/installer/installer_test.go
[MGMT-7635](https://issues.redhat.com/browse/MGMT-7635) Fix logs gathering on SNO when failing to complete bootstrapping
The log_sender command failed to mount /root/.ssh due to: "no such file or directory" error.
This code ensure the directory get created once the bootstrap flow begin
=> MGMT-7635 Fix logs gathering on SNO when failing to complete bootstrapping

src/common/common.go, src/common/common_test.go, test_files/mcs_logs.txt
Updated the regex to allow more chars between the host IP and 'Ignition'
this is required because in the MCS log the host IP is logged as scoped literal IPv6 address
e.g. [fe80::ff:fe9d:12ac%ens3]:42692
This should also allow master nodes to get updated to 'Configuring'
=> MGMT-7713 Worker won't get updated to 'Waiting for ignition' when installing with IPv6

src/ops/ops.go
=>  NO-ISSUE: Use -v for efibootmgr to get detailed output

Dockerfile.assisted-installer, Dockerfile.assisted-installer-controller
The original plan was to move all images to ubi8. This is not possible due to the lack
of some packages that are needed for other projects. We are now going to switch all images
to stream8 with the hope that the consistency accross repos will prevent (or help) with
debugging current/future issues in CI.
The goal is to keep component's builds as consistent as possible in the channels we are
releasing them on
=> MGMT-7760: Switch to stream8

deploy/assisted-installer-controller/assisted-installer-controller-nm.yaml, deploy/assisted-installer-controller/assisted-installer-controller-role.yaml, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go
Namespaces using run-level label are considered to be highly privileged
and Security Context Constrains are not applied to the workload running
in them.
One of the deployment models for assisted-installer uses cluster
deployed by the AI service to deploy next clusters. In this scenario, if
the same `assisted-installer` namespace is used for deploying Assisted
Service Operator, the pods do not get any securityContext properties
applied. This, apart from the potential security violations, causes
functional errors as e.g. Postgres container is running using wrong UID.
This PR changes configuration of the `assisted-installer` namespace so
that it does not have run-level label applied and is treated like any
other customer namespace.
Closes: …
=> Bug 1966621: Do not use run-level label for assisted-installer namespace

deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template
NO-ISSUE: add backofflimit 100 and imagePullPolicy: IfNotPresent to assisted controller
backofflimit 100 will allow us to see controller retrying in case we
reached timeout and controller failed for unknown reason
=> NO-ISSUE: add backofflimit 100 and imagePullPolicy: IfNotPresent to assisted controller

src/assisted_installer_controller/assisted_installer_controller.go, src/config/config.go, src/config/dry_run_config.go, src/config/flag_array.go, src/installer/installer.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/main/assisted-installer-controller/drymock/dry_mode_k8s_mock.go, src/main/main.go, src/ops/mock_ops.go, src/ops/ops.go, src/utils/utils.go
This commit introduces a dry run mode to the installer and the
controller. The mode is activated in both components when the
`DRY_ENABLE=true` environment is set (or when the `--dry-run`
flag is passed to them).
On the installer, the dry run mode disables several destructive actions
performed by the installer. The purpose of the dry run mode in the installer
is mostly allowing us to run a lot of installers on the same machine, without
causing harm to that machine, but still communicating with the service. This is useful
when performing load testing to the service.
See the diff for the exact actions that were disabled, but here's a
summary -
- `extractIgnitionToFS` skipped (it's not needed if we're not really
installing, and multiple installers running on the same machine
may compete on …
=> MGMT-8064: Introduce dry run mode to the installer

src/inventory_client/inventory_client.go
[MGMT-7912](https://issues.redhat.com/browse/MGMT-7912): getmonitors operator cache should not return value on any error
=> MGMT-7912: getmonitors operator cache should not return value on any

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go
[MGMT-8240](https://issues.redhat.com/browse/MGMT-8240): Controller should validate that console and cvo statuses 
were both updated in service
In case we failed to send console operator status but succeeded cvo we will stuck in finalizing
[MGMT-8238](https://issues.redhat.com/browse/MGMT-8238): assisted-controller should send all logs and not just the last 2 hours
=> Latest triage issues fixes

src/config/dry_run_config.go, src/k8s_client/k8s_client.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/main/drymock/dry_mode_k8s_mock.go, src/main/main.go, src/ops/ops.go
In multi-node cluster, the bootstrap node tries to connect to the
control plane started by the other control plane nodes.
In dry mode, this control plane doesn't really exist, so it has to be
mocked similarly to how we mock the cluster for the controller in dry
mode.
This commit adds this mocking to the installer to support multi-node
clusters
=> MGMT-8064: Dry mode multi-node cluster support

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go
`updateConfiguringStatusIfNeeded` gets passed `assistedNodesMap` which
at that point may already contain stale data if any of conditions in the
loop above it are met.
As a result, when it's time to set the configuring status for that host,
the service will respond with an error because that host already has stage
"done" (due to the condition in the loop mentioned previously) and you may
not go from stage "done" to stage "configuring".
`notValidStates` in `SetConfiguringStatusForHosts` was supposed to prevent
this from happening but since it's using stale data, that check fails.
Currently when the controller gets error responses from the service it retries
a few times and only gives up after about 15 retries (with 2 seconds in between).
If you try to install a cluster with 100 hosts and …
=> MGMT-8781: Fix controller updating configuring status with stale data

src/assisted_installer_controller/assisted_installer_controller.go, src/config/dry_run_config.go, src/inventory_client/inventory_client.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/main/drymock/dry_mode_k8s_mock.go, src/main/main.go, src/ops/mock_ops.go, src/ops/ops.go
Installing multi-node clusters using dry-mode / swarm had some
performance issues that are solved in this commit:
- Let the controller know about the reboot marker path of each and every
one of the cluster hosts. This allows it to mock the creation of k8s
node objects for each node only once that host actually reboots. This
prevents some odd race conditions.
Since we now need to give the controller even more per-host
information, the comma seperated `DryRunHostnames` and `DryMcsAccessIps`,
along with the new reboot marker path information, have been merged
into a single `DryRunClusterHosts` parameter which is a JSON
representing that information about all hosts in the cluster.
- Rename `defaultMaxRetries` to `DefaultMaxRetries`
- In installer dry run mode, use …
=> MGMT-8064: Improve performance of installer/controller dry mode in multi-node clusters

go.mod, go.sum
As a follow-up to 'update golang-jwt package' in the service: openshift/assisted-service#3108, updating the assisted-service package.
=> NO-ISSUE: update assisted-service package

go.mod, go.sum, src/inventory_client/inventory_client.go
This update to go-openapi/runtime exposed a bug in our url handling
where we add extra slashes to the url path.
Previously this seemed to have been cleaned up transparently by the
client but now ends up dropping the base path.
=> NO-ISSUE: Update go-openapi/runtime and fix url building

src/config/dry_run_config.go
`err` didn't get re-assigned so it always held a previously assigned
`nil` leading to an uninformative error message
=> NO-ISSUE: Fix error log printing the wrong error variable

Jenkinsfile
Jenkins build is broken on master since
https://github.com/openshift/assisted-installer/pull/412.
This fix tells to Jenkins to only build the images, since all the other
steps (lint, unit tests) are already part of Prow jobs.
=> NO-ISSUE: Jenkins should only build images

Jenkinsfile
Since https://github.com/openshift/assisted-installer/pull/414, jenkins
does not generate junit/coverage information, so we shoudn't publish
them.
=> NO-ISSUE: Fix jenkins build

Dockerfile.assisted-installer, Dockerfile.assisted-installer-build
This is the first step before updating assisted-service client and
models
Step two will be to update release repo and then update the code to
import the new client.
=> MGMT-9358: update containers golang version to 1.17

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/assisted_installer_controller/operator_handler.go, src/inventory_client/inventory_client.go, src/inventory_client/mock_inventory_client.go
As we are renaming the OCS operator to ODF, but on OCP4.8, we still have OCS operator. So, added a temporary fix that renames the operator name and subscription name to OCS for OCP version 4.8. This is to be removed after, OCP4.8 is removed from Saas day1 support.
Signed-off-by: Rewant Soni <resoni@redhat.com>
=> MGMT-8248: Hot fix for ODF

go.mod, go.sum, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/installer/installer.go, src/installer/installer_test.go, src/inventory_client/inventory_client.go, src/inventory_client/mock_inventory_client.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/main/assisted-installer-controller/assisted_installer_main_test.go
- When worker is waiting for 2 ready master nodes, ask only for masters
instead of all hosts
- Change locations that only need cluster without hosts, to request only
cluster.
/assign @filanov 
/assign @avishayt 
/assign @tsorya
=> MGMT-9709: Modify assisted installer, to use more efficient queries when accessing the assisted service

go.mod, go.sum, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/installer/installer.go, src/installer/installer_test.go, src/inventory_client/inventory_client.go, src/inventory_client/mock_inventory_client.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/main/assisted-installer-controller/assisted_installer_main_test.go
- When worker is waiting for 2 ready master nodes, ask only for masters
instead of all hosts
- Change locations that only need cluster without hosts, to request only
cluster.
This is backport to 2.5
Original PRs:
https://github.com/openshift/assisted-installer/pull/427
And 
https://github.com/openshift/assisted-installer/pull/435
/cc @filanov
=> Bug 2073998: Modify assisted installer, to use more efficient queries when accessing the assisted service

src/config/config.go, src/config/dry_run_config.go, src/installer/installer.go, src/k8s_client/k8s_client.go, src/main/drymock/dry_mode_k8s_mock.go, src/main/main.go, src/ops/ops.go, src/ops/ops_test.go
In order to enable running the assisted installer in the combined agent,
use of global variables have to be eliminated,
[MGMT-9991](https://issues.redhat.com//browse/MGMT-9991): Separate installer main function to contain only flag
processing and environment variables handling.
Move the rest of the functionality to separate function.
/cc @omertuc
=> MGMT-9985: Eliminate use of global variables in assisted-installer

src/installer/installer.go, src/installer/installer_test.go, src/ops/ops.go
In case ironic-agent.service exists on the node the assisted-installer will not reboot the node. 
Instead, it will stop the assisted-agent (agent.service) in order to let the ironic-agent know that the assisted-agent served its purpose, and let the ironic agent reboot the node
=> MGMT-9244: Prevent assisted-agent from rebooting the node when managed by IPA

.github/dependabot.yml
Since it requires D/S changes and changes in openshift/release repo, it isn't really something that we'd like to go in automatically.
In addition, we no longer need the ok-to-test label, as dependabot is a trusted-app.
=> NO-ISSUE: remove dependabot bumps of docker images

deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template
[MGMT-10348](https://issues.redhat.com//browse/MGMT-10348): backofflimit in assisted controller is set in a wrong place and does nothing
=> MGMT-10348: backofflimit in assisted controller is set in a wrong place and does nothing

.github/dependabot.yml
Reverting most of https://github.com/openshift/assisted-installer/pull/457 because we would still want to have reminders for new docker images.
For more context: https://github.com/openshift/assisted-installer-agent/pull/352#issuecomment-1123333744
/cc @omertuc @eliorerz
=> NO-ISSUE: Reverting removal of dependabot image bumps

src/installer/installer.go, src/installer/installer_test.go, src/ops/mock_ops.go, src/ops/ops.go
Cleanup Raid PVs and VGs before stopping it and removing the installation disk membership.
Solving "mdadm: Cannot get exclusive access to /dev/md0" When trying to stop a raid with LVM on it.
=> Bug 2086273: Cleanup disk which is part of a raid and have lvm on it

src/config/config.go, src/config/config_test.go, src/installer/installer.go
When adding a worker to a 2nd day cluster, HA mode is irrelevant, so
we shall not be passing it here.
It used to be the case that a day 2 worker could only be added to an HA
cluster. We are making this change to allow the addition of a day 2
worker to a non HA cluster.
The condition [1] was blocking this.
That validation ensures that Day 1 SNO clusters will only accept Master
or Bootstrap roles for the host being installed.
This change will validate that the installer has not been called with
high availability mode set for a worker, if this has occurred, the
installer will reject the request with an error.
[1] https://github.com/openshift/assisted-installer/blob/d67d2843d0e757ef5643e6c873b49e61ef83a0ea/src/config/config.go#L93-L99
=> MGMT-9379: Disregard HA mode for worker.

src/config/config.go, src/installer/installer.go, src/installer/installer_test.go
[MGMT-10003](https://issues.redhat.com//browse/MGMT-10003): save-partlabel and save-partindex coreos-installer args are not honored because the partition is formatted previously
If skip-installation-disk-cleanup is set don't cleanup installation disk
=> MGMT-10003: save-partlabel and save-partindex coreos-installer args are not honored because the partition is formatted previously

src/config/config.go, src/config/config_test.go, src/config/dry_run_config.go, src/main/main.go
After merging [MGMT-9379](https://issues.redhat.com//browse/MGMT-9379) it was found that the parameter changes that we
applied to HighAvailabilityMode were ineffective in the installer.
After tracking down the root cause, the problem was that the command
line arguments were being parsed twice, once for the main arguments and
once again for the "dry run arguments". On the second parse, the changes
we made to the first parse were overwritten, rendering them ineffective.
This PR fixes that by merging together the code that performs the parse
on main parameters and dry run arguments.
I also removed the static way of parsing arguments and replaced it with
a more "instance based" approach, this is cleaner, causes less confusion
and is also more testable as we can pass an args array to it.
As a …
=> MGMT-9379: Fix arguments to make sure that HighAvailabilityMode is updated correctly to ensure it is unset for workers.

src/ops/ops.go
Bug 2055978: host fail to boot from installation disk in case of multiple active "Red Hat Enterprise Linux" boot entries
Removing duplicate efi boot entries
=> Bug 2055978: host fail to boot from installation disk in case of multiple active "Red Hat Enterprise Linux" boot entries

src/installer/installer.go, src/installer/installer_test.go
[MGMT-10450](https://issues.redhat.com//browse/MGMT-10450): Timeout writing to disk reported from bootstrap node when failing to start bootkube
After writing to disk we will update status to waiting for control plane
with info relevant to the state
=> MGMT-10450: Timeout writing to disk reported from bootstrap node when failing to start bootkube

src/installer/installer.go, src/installer/installer_test.go
The comment above the restart call states:
`restart NetworkManager to trigger NetworkManager/dispatcher.d/30-local-dns-prepender`
In SNO, this script does not exist since SNO is none-platform and that
script is only created by the installer in other platforms.
Since this script doesn't exist on SNO, there's no point in restarting
NetworkManager on SNO to trigger it to run.
The reason we avoid the restart is because we have a suspicion it might
be related to a bug we observe with SNO that we can't really explain:
https://issues.redhat.com/browse/MGMT-10330
/cc @tsorya
=> MGMT-10330: Do not restart network manager on single node clusters

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/ops/ops.go
NO-ISSUE: In case must-gather upload failed but logs were gathered already we should retry only upload part
=> NO-ISSUE: In case must-gather upload failed but logs were gathered already we should retry only upload part

deploy/assisted-installer-controller/assisted-installer-controller-role.yaml, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/k8s_client/k8s_client.go, src/k8s_client/mock_k8s_client.go, src/utils/utils.go
MGMT-11100: Adding get router status logic in case of sno failure.
Currently we have known issue in sno flow where router healthcheck fails
from pods network. This pr add verification that router is reachable
from host network and enables router access log.
This change is temporary till we will not find an issue we encountered
=> MGMT-11100: Add router get router status logic in case of sno failure

src/inventory_client/inventory_client.go
[MGMT-8855](https://issues.redhat.com//browse/MGMT-8855): repeated event messages in wait for olm operators due to cache hits
=> MGMT-8855: repeated event messages in wait for olm operators due to cache hits

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/common/common.go, src/main/assisted-installer-controller/assisted_installer_main.go
[MGMT-11106](https://issues.redhat.com//browse/MGMT-11106): Writing controller logs to file in order to be able to send them in case of kube-api failure
Adding file handler to assisted-controller logger. Upload logs will send logs from log file in case we failed to reach kube-api to read those logs. In case something is wrong with file and kube-api we will send error message.
File will be created in /tmp in order not to handle user premissions in k8s
=> MGMT-11106: Writing controller logs to file in order to be able to send

src/ops/ops.go
When having LVM on top of software raid, the name of the device reported by mdadm is a symlink to the real block device in /dev, causing problems identifying which LVM volume groups need to be removed before cleaning the RAID
This should fix that issue
=> MGMT-10085: Get real filepath of RAID device

Dockerfile.assisted-installer-build, src/assisted_installer_controller/assisted_installer_controller_test.go, src/ops/ops.go
Backports https://github.com/openshift/assisted-installer/pull/510.
=> [release-ocm-2.5] MGMT-11365: fix flaky installation of golangci-lint (#510)

src/main/assisted-installer-controller/assisted_installer_main.go
The aim is to make it easier to determine where in the codebase an error originates from.
=> MGMT-11170: Report the caller in the log.

src/installer/installer.go, src/installer/installer_test.go, src/ops/mock_ops.go, src/ops/ops.go, src/ops/ops_test.go
If you have more than one phisical volume assigned to a volume group in disk that we need to wipe, only the first volume group is deleted during cleanup, this causes problems later because there are still existing volume groups in use
This commit addresses that by ensuring that all volume groups are considered.
/cc @omertuc
/cc @paul-maidment
=> MGMT-11695: Remove all LVM volume groups for installer disk

deploy/assisted-installer-controller/assisted-installer-controller-role.yaml, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/assisted_installer_controller/operator_handler.go, src/k8s_client/k8s_client.go, src/k8s_client/mock_k8s_client.go
[MGMT-11565](https://issues.redhat.com//browse/MGMT-11565): Add handleOLMEarlySetupBug when waiting for CSV
- Waiting for ClusterServiceVersion for operators now actually waits for
a real CSV and not just CSV name in the subscription status, because
the latter doesn't seem to mean much
- When we wait for CSV and it doesn't exist yet, we also check if there are failed olm jobs
if they are, we delete those jobs and delete install plan.
It will force olm to recreate failed jobs and restart installation
=> MGMT-11565: Add handleOLMEarlySetupBug when waiting for CSV

Dockerfile.assisted-installer, Dockerfile.assisted-installer-controller, Makefile
Let Dockerfile and Makefile respond to TARGETPLATFORM setting which is
set by docker buildx when building multi-arch images.
/cc @tsorya
=> MGMT-11348: Changes for upstream multi-arch support

Dockerfile.assisted-installer-build
2.4 jobs in assisted-installer are failing to build docker images with
the following error:
```
/go/pkg/mod/golang.org/x/sys@v0.0.0-20220909162455-aba9fc2a8ff2/unix/syscall.go:83:7: undefined: unsafe.Slice
/go/pkg/mod/golang.org/x/sys@v0.0.0-20220909162455-aba9fc2a8ff2/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
/go/pkg/mod/golang.org/x/sys@v0.0.0-20220909162455-aba9fc2a8ff2/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17
```
References:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-installer-release-ocm-2.4-mirror-nightly-image/1569893960787169280
Same issue as in https://github.com/openshift/assisted-installer-agent/pull/434
=> MGMT-12050: Pinning golang.org/x/sys dependency due to golang incompatibility

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/k8s_client/k8s_client.go, src/k8s_client/mock_k8s_client.go
[MGMT-12057](https://issues.redhat.com//browse/MGMT-12057): Remove enablement of router access logs in controller, not needed anymore
=> MGMT-12057: Remove enablement of router access logs in controller, not needed anymore

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go
[MGMT-12070](https://issues.redhat.com//browse/MGMT-12070): Assisted controller should not set status done on host more than once #543
=> MGMT-12070: Assisted controller should not set status done on host more than once

src/assisted_installer_controller/assisted_installer_controller.go, src/common/common.go
[MGMT-12055](https://issues.redhat.com//browse/MGMT-12055): Assisted controller should log if one of the nodes changed it's ip after reboot
=> MGMT-12055: Assisted controller should log if one of the nodes changed it's ip after reboot

src/ops/mock_ops.go, src/ops/ops.go
RemoveLV is not used anywhere, nor needed to cleanup LVM
=> NO-ISSUE: Remove unused function RemoveLV

deploy/assisted-installer-controller/assisted-installer-controller-nm.yaml
OCPBUGS-3166: assisted-installer: pod creation fails due to violations of security policies in 4.12
Adding privileged labels to namespace
=> OCPBUGS-3166: assisted-installer: pod creation fails due to violations of security policies in 4.12

Dockerfile.assisted-installer-build
``go get`` might result in ``go.mod`` changes meaning we might use different dependencies versions than intended.
In addition, this kind of usage of ``go get`` is deprecated in go 1.17 and is blocked in go version >= 1.19.
=> change all 'go get' commands to 'go install'

Dockerfile.assisted-installer, Dockerfile.assisted-installer-build, Dockerfile.assisted-installer-controller, go.mod, src/assisted_installer_controller/operator_handler.go, src/ignition/mock_ignition.go, src/inventory_client/mock_inventory_client.go, src/k8s_client/mock_k8s_client.go, src/ops/execute/mock_execute.go, src/ops/mock_ops.go
Due to several CVE bugs we need to update golang version to >= v1.18.1.
https://bugzilla.redhat.com/show_bug.cgi?id=2077688
https://bugzilla.redhat.com/show_bug.cgi?id=2077689
This PR updates golang version to v1.18.1 and golangci to v1.46.0.
/cc @eliorerz
=> OCPBUGSM-46219: OCPBUGSM-46220: Update golang version to 1.18.1.

src/assisted_installer_controller/operator_handler.go
Currently the operator handler checks if the operator is available in the service, but it doesn't take into account that the operator may have been removed from the list of managed operators. That results in a nil pointer exception and a crash of the controller. This patch fixes that adding a nil check to the relevant code.
Related: https://issues.redhat.com/browse/MGMT-12471
=> MGMT-12471: Don't crash if operator isn't monitored by service

src/installer/installer.go, src/installer/installer_test.go, src/ops/mock_ops.go, src/ops/ops.go, src/ops/ops_test.go, src/utils/utils.go, src/utils/utils_test.go
Forcing the removal of affected DeviceMapper devices should fix the problems when properly running disk_speed_check before disk cleanup
/cc @vrutkovs 
/cc @paul-maidment
=> MGMT-12339: Add extra step to force clean disks with LVM volumes

src/installer/installer.go, src/installer/installer_test.go
Update the host install progress with a message if disk cleanup failed. This way we can catch it in assisted-service and emit an event that will ease debugging
/cc @eranco74
=> MGMT-12339: Update host install progress on cleanup error

src/assisted_installer_controller/assisted_installer_controller.go, src/main/assisted-installer-controller/assisted_installer_main.go
[MGMT-13141](https://issues.redhat.com//browse/MGMT-13141): assisted-installer-controller shouldn't try to update BMH if the cluster platform is not BareMetal
=> MGMT-13141: assisted-installer-controller shouldn't try to update BMH if the cluster platform is not BareMetal

go.sum
CVE-2021-4238 goutils: RandomAlphaNumeric and CryptoRandomAlphaNumeric are not as random as they should be
https://bugzilla.redhat.com/show_bug.cgi?id=2156729
Randomly-generated alphanumeric strings contain significantly less entropy than expected. The RandomAlphaNumeric and CryptoRandomAlphaNumeric functions always return strings containing at least one digit from 0 to 9. This significantly reduces the amount of entropy in short strings generated by these functions.
https://github.com/Masterminds/goutils/commit/869801f20f9f1e7ecdbdb6422049d8241270d5e1
https://pkg.go.dev/vuln/GO-2022-0411
=> OCPBUGS-5715: CVE-2021-4238 assisted-installer-container: goutils

src/ops/ops.go
Execute shutdown -r now instead of 1 minute from now this should save 1 minute during the installation
The side effect of this change is that the agent will not report back the install command result upon success
This side effect can be mitigated by adding inhibit lock on the agent side that will prevent the node from rebooting until the agent allow it.
=> MGMT-13131: shorten SNO installation duration

deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/ops/ops.go
[MGMT-13229](https://issues.redhat.com//browse/MGMT-13229): SNO: Start controller when node is not ready, right after joined
 We want to start controller as fast as possible after reboot and to minimize time when we don't know what is going on.
This will allow us to start when kubelet will join to itself and we will be able
to send joined stage to service and wait till node will become ready while controller is running already.
In order to start running while control plane kube-api doesn't exists yet , going to use bootstrap kubeconfig as it is part of filesystem.
=> MGMT-13229: SNO: Start controller when node is not ready, right after joined

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/common/common.go, src/utils/tarutil.go, src/utils/tarutil_test.go
[MGMT-13463](https://issues.redhat.com//browse/MGMT-13463): Assisted-controller can fail to send summary logs and we will not have any logs
Sometimes controller can fail to stream tar.gz of must-gather and no files will be send as we will close write pipe and will not try to stream another tar entry.
This change will log the error but will try to stream all other tar entries we pass to the stream function
=> MGMT-13463: Assisted-controller can fail to send summary logs and we  will not have any logs

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go
[MGMT-13507](https://issues.redhat.com//browse/MGMT-13507): Apply node labels only when node is Ready
Juniper have a problem with their deployment in case we apply node labels before node is read.
In order to fix it we should apply them only in case node is ready
=> MGMT-13507: Apply node labels only when node is Ready

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go
[MGMT-13595](https://issues.redhat.com//browse/MGMT-13595): Allow moving node from rebooting to joined
Sometimes we are missing configuring state due to different issue and installaiton will be blocked, we want to allow controller to move node from rebooting to joined in order to continue
=> MGMT-13595: Allow moving node from rebooting to joined

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/assisted_installer_controller/operator_handler.go, src/k8s_client/k8s_client.go, src/k8s_client/mock_k8s_client.go, src/main/drymock/dry_mode_k8s_mock.go
This is a backport of [MGMT-12471](https://issues.redhat.com//browse/MGMT-12471) for ACM 2.6. It contains the changes in pull requests #574 and #589.
This patch changes the controller so that it doesn't wait for the console operator when the console capability is explicitly disabled.
Related: https://issues.redhat.com/browse/MGMT-13657
Related: https://issues.redhat.com/browse/MGMT-12471
Related: https://github.com/openshift/assisted-installer/pull/574
Related: https://github.com/openshift/assisted-installer/pull/589
=> MGMT-13657: Don't wait for console if it is disabled - ACM 2.6

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/installer/installer.go, src/installer/installer_test.go, src/k8s_client/k8s_client.go, src/k8s_client/mock_k8s_client.go, src/main/assisted-installer-controller/assisted_installer_main.go
Since 4.13 cloud controller is external and requires valid
vSphere credentials  to remove uninitialized taint, which blocks
bootstrap. This change will make assisted-installer watch nodes and remove
the taint once it appears to complete installation - both on bootstrap and post-control-plane.
Verified that installed no longer gets stuck on latest nightly, needs https://github.com/openshift/release/pull/36133 to make sure it works in CI
=> MGMT-13605: Remove uninitialized taint from vSphere nodes

src/assisted_installer_controller/operator_handler.go
This is a backport of [MGMT-12471](https://issues.redhat.com//browse/MGMT-12471) for ACM 2.7. It includes the changes in pull request #589. The changes in pull request #574 are alse necessary, but they are included in the ACM 2.7 branch already.
Currently the operator handler checks if the operator is available in the service, but it doesn't take into account that the operator may have been removed from the list of managed operators. That results in a nil pointer exception and a crash of the controller. This patch fixes that adding a nil check to the relevant code.
Related: https://issues.redhat.com/browse/MGMT-13664
Related: https://issues.redhat.com/browse/MGMT-12471
Related: https://github.com/openshift/assisted-installer/pull/589
Related: …
=> MGMT-13664: Don't crash if operator isn't monitored by service - ACM 2.7

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/assisted_installer_controller/operator_handler.go, src/inventory_client/inventory_client.go, src/utils/utils.go
[MGMT-13710](https://issues.redhat.com//browse/MGMT-13710): assisted-installer-controller hangs for 2 minutes before uploading the ingress CA
Optimizing WaitForPredicateWithTimer first to run function and only then wait for interval.
Ingress CA upload should retry quickly.
Optimizing wait for operator is available by rechecking operator status in service right after update operator status to available
=> MGMT-13710: assisted-installer-controller hangs for 2 minutes before uploading the ingress CA

src/ops/ops.go, src/ops/ops_test.go
For powervm, using the bootlist to set target disk as boot device.
Signed-off-by: CS Zhang <zhangcho@us.ibm.com>
=> MULTIARCH-3387: Set boot device to target disk for powervm

src/main/assisted-installer-controller/assisted_installer_main.go
[MGMT-14114](https://issues.redhat.com//browse/MGMT-14114): Nutanix - uninitialized set on nodes
Setting removeuninitializedtaint to true in case of nutanix, same as vpshere
=> MGMT-14114: Nutanix - uninitialized set on nodes

deploy/assisted-installer-controller/assisted-installer-controller-network-policy.yaml
[MGMT-12967](https://issues.redhat.com/browse/MGMT-12967)
Creates an empty network policy for the spoke cluster's assisted-installer namespace. The namespace was created by default and failed the compliance operator's scans due to a lack of a network policy.
1. Used assisted-test-infra, deployed assisted-service and installed a multi-node spoke cluster with the changes in the assisted-installer
2. Checked the spoke cluster to make sure the assisted-installer namespace and the empty network policy existed
3. Deployed the compliance operator ([src](https://docs.openshift.com/container-platform/4.10/security/compliance_operator/compliance-operator-installation.html#installing-compliance-operator-cli_compliance-operator-installation))
4. Created 3 PVs for the results
5. Ran the compliance …
=> MGMT-12967: Create network policy in assisted-installer namespace

src/installer/installer.go, src/installer/installer_test.go
https://issues.redhat.com/browse/MGMT-13586
There have previously been issues where the bootstrap node will reboot before ETCD is ready. This change waits for the new status provided by the ETCD operator before rebooting the bootstrap node.
=> MGMT-13586: Wait for ETCD Bootstrap to complete

go.mod, go.sum, vendor/modules.txt
The package github.com/masterminds/vcs before 1.13.3 are vulnerable to Command Injection via argument injection. When hg is executed, argument strings are passed to hg in a way that additional flags can be set. The additional flags can be used to perform a command injection.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2215317 
Additional References:
* https://github.com/Masterminds/vcs/pull/105
* https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMMASTERMINDSVCS-2437078
=> OCPBUGS-15068 CVE-2022-21235 github.com/Masterminds/vcs command inj

Makefile
https://issues.redhat.com/browse/MGMT-15235
In order to be FIPS compliant, we need to compile
all go code with CGO_ENABLED=1.
/cc @filanov
=> MGMT-15235: Compile with CGO_ENABLED=1 for FIPS

Makefile
https://issues.redhat.com/browse/MGMT-15235
In order to be FIPS compliant, we need to compile
all go code with CGO_ENABLED=1.
The original cherry pick of the PR for master failed https://github.com/openshift/assisted-installer/pull/683#issuecomment-1633186997
=> [release-ocm-2.6] MGMT-15235: Compile with CGO_ENABLED=1 for FIPS

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go
[MGMT-15344](https://issues.redhat.com//browse/MGMT-15344): Assisted-controller should not timeout on waiting cvo by itself
=> MGMT-15344: Assisted-controller should not timeout on waiting cvo by itself

Makefile
Reverts openshift/assisted-installer#683
Multi-arch build errors occur because of the initial change.
Reverting until further investigation can be completed.
See slack thread https://redhat-internal.slack.com/archives/C014N2VLTQE/p1690385559654819
=> Revert "MGMT-15235: Compile with CGO_ENABLED=1 for FIPS"

Makefile
https://issues.redhat.com/browse/MGMT-15235
To be FIPS-compliant, CGO_ENABLED=1 flag must be
specified for go code.
This flag along with the base image used doesn't
work for architectures other than amd64.
See previous revert PR for more information
https://github.com/openshift/assisted-installer/pull/693
Slack thread discussion
https://redhat-internal.slack.com/archives/C014N2VLTQE/p1690385559654819
/cc @gamli75 @filanov
=> MGMT-15235: Compile with CGO_ENABLED=1 for amd64

Dockerfile.assisted-installer-build
Cannot update golangci-lint in the same PR as one exhibiting issues because the CI still uses the previous version.
Updating k8s.io/apimachinery module to a newer version causes the old linter to throw nil pointer error.
Example https://github.com/openshift/assisted-installer/pull/701
=> OCPBUGS-16482: bump golangci-lint to 1.53.1

src/installer/installer.go, src/installer/installer_test.go
https://issues.redhat.com/browse/MGMT-13586
There have previously been issues where the bootstrap node will reboot before ETCD is ready. This change waits for the new status provided by the ETCD operator before rebooting the bootstrap node.
Cherry pick of https://github.com/openshift/assisted-installer/pull/670
/cc @tsorya
=> MGMT-13586: Wait for ETCD Bootstrap to complete (#670)

.github/dependabot.yml
Move excluded to ignore list.
- excluded are excluded from the group only.
- ignored are removed from the dependency tree ( i.e. golang )
=> NO-ISSUE: fix dependable ignored packages

Dockerfile.assisted-installer, Dockerfile.assisted-installer-controller
Now that D/S building system fully supports RHEL-9 base images (and allows easy installation of nmstate and other libs that were previously unsupported) we can move U/S to stream9 and D/S to ubi9-minimal.
It doesn't seem possible to easily use ubi9-minimal U/S for the assisted-service, because installation of nmstate packages either requires entitlements running on a RHEL node, or alternatively an access to RedHat's internal network (which can be a major problem for U/S development). For a better consistency we're sticking with the same for the agent, installer, etc.
=> MGMT-15810: change base image to stream9

Dockerfile.assisted-installer
It seems like we were missing an explicit installation for the nsenter executable which does not exist by default in stream9 base image.
The resulting errors are:
```
level=info msg="failed executing nsenter [--target 1 --cgroup --mount
--ipc --pid -- vgs --noheadings -o vg_name,pv_name], env vars
[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HTTPS_PROXY= http_proxy= NO_PROXY= HTTP_PROXY= TERM=xterm
container=podman BUILD_LOGLEVEL=0
OPENSHIFT_BUILD_NAME=assisted-installer
OPENSHIFT_BUILD_NAMESPACE=ci-op-8g1imlzt https_proxy= no_proxy=
HOME=/root HOSTNAME=test-infra-cluster-3119ce36-master-2], error exec:
\"nsenter\": executable file not found in $PATH, waitStatus 0, Output
\"\""
```
(see
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assist …
=> MGMT-15810: fix image missing nsenter executable

src/config/config.go, src/installer/installer.go, src/installer/installer_test.go, src/ops/mock_ops.go, src/ops/ops.go, src/ops/ops_test.go
iIf skip mco reboot is enabled (passed as argument), skip mco reboot is applied.  This logic consists from:
- Extracting the encapsulated machine config from ignition, that contains both the os-image and the kernel arguments needed for reboot avoidance.
- Calling ostree command to write os image with the expected kernel arguments.
=> MGMT-15710: Assisted installer changes for avoiding MCO reboot

src/installer/installer.go, src/ops/ops.go, src/ops/ops_test.go
This causes the file system to become corrupt in some cases.
In addition - move the 'change boot order' operation after 'skip mco reboot'
/cc @filanov 
/cc @tsorya
=> MGMT-15984: Assisted installer doesn't freeze and unmount file systems used for overwriting os image

src/assisted_installer_controller/assisted_installer_controller_test.go, src/assisted_installer_controller/operator_handler.go
Installing operators fails due to failing job, The job are starting and timing out because workers aren't ready.
deleting the failed job to allow retry of operator installation. The solution is removing failed `OLM jobs` and `subscription install plans` during operator initialization check not only in the case of `notFound` error. Linking test installation same as in the origin failure -  http://rdu-infra-edge-06.infra-edge.lab.eng.rdu2.redhat.com:6008/clusters/5a46e946-60fe-43ab-8650-5a50c0429bf6
=> MGMT-15926: Operators installation fails due to timeout on failed jobs

src/ops/ops.go, src/ops/ops_test.go
For SCSI or SATA disks the partition number is appended to the device. For nvme disks, "p" and then the partition number is appended to the device.
When overwriting OS image, the correct naming has to be used.  Otherwise the partition may not exist and skipping MCO reboot will be aborted.
/cc @tsorya 
/cc @filanov
=> MGMT-16258:  Partitions naming convetion is different for various disk types

src/main/assisted-installer-controller/assisted_installer_main.go, src/main/assisted-installer-controller/assisted_installer_main_test.go
assisted-service runs on the bootstrap node in agent-based installations. assisted-service becomes unavailable after the bootstrap completes and when the bootstrap node reboots to join the control plane. When assisted-service becomes unavailable, assisted-installer-controller is then unable to retrieve the list of hosts. The call to retrieve the host list fails and the waitAndUpdateNodesStatus function breaks and retries again. This is a problem because the code that removes the taint happens further down in the function and is now unable to be exercised.
The consequence is the taint is not removed for the bootstrap node and any worker nodes.
The fix adds an alternative mechanism to remove the uninitialized taint for agent-based installs. This mechanism works without the presence of …
=> OCPBUGS-20049: Remove uninitialized taint for agent-based installs

Dockerfile.assisted-installer-build
app-sre made their repo mirroring golangci-lint private for legal reasons, and
now our jobs are failing to install it. Installing it now from the cli.
We could also have pulled golangci-lint from dockerhub, but rate
limitation there is quite aggressive.
=> MGMT-16370: fix golangci-lint failing to be pulled

src/assisted_installer_controller/reboots_notifier.go, src/assisted_installer_controller/reboots_notifier_test.go, src/utils/utils.go
There are many possible failures.  Many of these failures are temporary such as API is not reachable, or failure to create debug pod. Added retry for the retrieval of number of reboots
/cc @filanov
=> MGMT-16266: Indication event showing how often host has been rebooted missing on some nodes

go.mod, go.sum, vendor/github.com/docker/docker/api/types/filters/parse.go, vendor/github.com/docker/docker/api/types/registry/registry.go, vendor/modules.txt
https://issues.redhat.com/browse/MGMT-14226
Upgrades go dependency github.com/docker/docker to 20.10.24 to fix CVE. GHSA-33pg-m6jh-5237
=> MGMT-14226: Upgrade docker to 20.10.24 for CVE-2023-28842

go.mod, go.sum, vendor/github.com/docker/docker/api/types/container/hostconfig_unix.go, vendor/github.com/docker/docker/api/types/filters/parse.go, vendor/github.com/docker/docker/api/types/registry/registry.go, vendor/modules.txt
Cherry-pick of PR https://github.com/openshift/assisted-installer/pull/781
https://issues.redhat.com/browse/MGMT-14226
Upgrades go dependency github.com/docker/docker to 20.10.24 to fix CVE. GHSA-33pg-m6jh-5237
/cc @gamli75
=> [release-ocm-2.9] MGMT-14226: Upgrade docker to 20.10.24 for CVE-2023-28842 (#781)

src/ops/ops.go, src/ops/ops_test.go
When skipping MCO reboot, the last partition is extended to fill the remaining free space in the disk. This may be undesirable since there are scenarios that a user adds a partition in the installation disk.
This change doubles the space occupied by the last disk partition instead of occupying all the remining space.  The assumption is that doubling the space should be enough for image overwrite.
/cc @javipolo
=> MGMT-16966: Problem creating extra partition on main disk in 4.15+

src/installer/installer.go, src/installer/installer_test.go
https://issues.redhat.com/browse/MGMT-16843
Some processes during install time depend on the hostname and an invalid hostname (e.g. 'localhost', having capital letters, etc.) that could cause the install to fail.
Extra validation is added when checking the hostname to ensure it is valid. A random hostname will be assigned if the current hostname is invalid.
See above issue for an example of the scenario with an invalid hostname fails to install.
/cc @omertuc @gamli75
=> MGMT-16843: Ensure valid hostname during install

src/installer/installer.go, src/installer/installer_test.go, vendor/github.com/openshift/assisted-service/pkg/validations/validations.go, vendor/modules.txt
Cherry pick of PR https://github.com/openshift/assisted-installer/pull/788 
https://issues.redhat.com/browse/MGMT-16843
Some processes during install time depend on the hostname and an invalid hostname (e.g. 'localhost', having capital letters, etc.) that could cause the install to fail.
Extra validation is added when checking the hostname to ensure it is valid. A random hostname will be assigned if the current hostname is invalid.
/cc @gamli75
=> [release-ocm-2.8] MGMT-16843: Ensure valid hostname during install

src/installer/installer.go, src/installer/installer_test.go, vendor/github.com/openshift/assisted-service/pkg/validations/validations.go, vendor/modules.txt
Cherry pick of PR https://github.com/openshift/assisted-installer/pull/788 
https://issues.redhat.com/browse/MGMT-16843
Some processes during install time depend on the hostname and an invalid hostname (e.g. 'localhost', having capital letters, etc.) that could cause the install to fail.
Extra validation is added when checking the hostname to ensure it is valid. A random hostname will be assigned if the current hostname is invalid.
/cc @gamli75
=> [release-ocm-2.9] MGMT-16843: Ensure valid hostname during install

Dockerfile.assisted-installer-build, src/installer/installer.go, src/installer/installer_test.go, vendor/github.com/openshift/assisted-service/pkg/validations/validations.go, vendor/modules.txt
Cherry pick of PR https://github.com/openshift/assisted-installer/pull/788 
https://issues.redhat.com/browse/MGMT-16843
Some processes during install time depend on the hostname and an invalid hostname (e.g. 'localhost', having capital letters, etc.) that could cause the install to fail.
Extra validation is added when checking the hostname to ensure it is valid. A random hostname will be assigned if the current hostname is invalid.
/cc @gamli75
=> [release-4.14] MGMT-16843: Ensure valid hostname during install

src/ops/ops.go
When adding a partition on installation disk, the partition is part of ignition that contains machine config.  The ignition has a version and may contain some fields that are present only in later versions of coreos-ignition.
Since the basic ignition served by machine-config-server has version 2.2, when there is parition in a ignition 3.*, the MCS refuses to serve
the content with internal server error.  In order to overcome this, a
header "Accept: application/vnd.coreos.ignition+json; version=3.4.0" is added which instructs MCS to convert the returned ignition to 3.4.0
/cc @tsorya 
/cc @javipolo
=> MGMT-16993: [STG] avoid reboot not working correctly when there is a partition on installation disk

src/installer/installer.go
When the function ops.GetEncapsulatedMC takes too long, the host stage 'Writing image to disk' times out since retry is used.
This changes the machanism to timeout instead of retry.
/cc @tsorya
=> MGMT-17384: Change waiting for encapsulated machine config from retry to wait-for-predicate

Dockerfile.assisted-installer-build
The reference to the quay image has been replaced with
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/bin v1.53.2
If we leave this unchanged, the skipper build container fails with an error about a missing image.
=> MGMT-17541: Replace broken golangci reference

src/installer/installer.go, src/inventory_client/inventory_client.go
In the race between assisted-installer on the bootstrap node and assisted-installer-controller on the cluster control plane to mark nodes as Joined, a win for the assisted-installer-controller would cause the bootstrapping process to lock up for 30+ minutes.
Prevent this by not retrying HTTP requests that receive a 409 response at the HTTP transport level. Instead, retry at the logic level and avoid making requests that cannot succeed.
=> OCPBUGS-32105: Fix race to mark node Joined

src/installer/installer.go, src/ops/ops.go
Hosts may not restart before beginning installation
so if we generate a random hostname, it won't take
effect unless we use hostnamectl to actually replace
the hostname live.
=> MGMT-16843: Use hostnamectl to replace illegal hostname

deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/reboots_notifier.go, src/assisted_installer_controller/reboots_notifier_test.go, src/config/config.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/ops/ops.go
In order to provide the number of reboots for installed node, "oc debug" is used and then the command "last reboot".  "oc debug" uses external image called "support-tools".  This image is not part of standard installation and it is not available in disconnected environments. Therefore, this notification is removed from the controller.
/cc @tsorya
=> MGMT-17353: Debug pod left in ImagePullBackOff after install in disconnected environment

Dockerfile.assisted-installer, Dockerfile.assisted-installer-controller
[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
=> [release-ocm-2.9] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid

Dockerfile.assisted-installer, Dockerfile.assisted-installer-controller
[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
=> [release-ocm-2.7] NO-ISSUE:  Use archived dnf repositories for centos8 as the current ones are no longer valid

Dockerfile.assisted-installer, Dockerfile.assisted-installer-controller
[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
=> [release-ocm-2.8] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid

Dockerfile.assisted-installer-build
Replace base golang image in the build Dockerfile as it is based on centos7 and it is EOL, which results in yum can't reach its repositories
=> NO-ISSUE: Replace base golang image in the build Dockerfile

src/installer/installer.go
In a race between the assisted-installer and
assisted-installer-controller to mark a control plane node as ready, the former will get a 409 Conflict response from assisted-service if the latter wins. Since f548d3284a438c8e2020253d2250620b095c70a1 we retry that check promptly. However, prior to this change we never read fresh inventory data (which would show the host has already reached the "installed" state and thus prevent us from attempting another (unnecessary) write that is doomed to fail due to a conflict.
Reload the host inventory in the event of a failure to update the host status, so that we can take into account that the change may already have been performed by the assisted-installer-controller.
=> OCPBUGS-36779: Reload host inventory on conflict

go.mod, go.sum, vendor/github.com/rh-ecosystem-edge/preinstall-utils/pkg/disk_ops.go, vendor/modules.txt
The purpose of this PR is to pick up a change to disk cleanup made in https://github.com/rh-ecosystem-edge/preinstall-utils/commit/cf015589a8b3b0ec90c439661c41c91a8fa5b0f9
This change is to ensure that in the case of thin provisioning we clean up all necessary disks in the correct order.
This has been tested in assisted-test infra with a 5 node cluster and an artificially created thin provisioning, the cluster installs correctly where it would not have done so before this change.
=> OCPBUGS-31570: Bump to latest preinstall utils for disk cleanup fixes

Dockerfile.assisted-installer, Dockerfile.assisted-installer-controller
This PR moves centos base image from stream8 to stream 9 as well as stream8 is EOL
=> [release-ocm-2.8] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

Dockerfile.assisted-installer, Dockerfile.assisted-installer-controller
This PR moves centos base image from stream8 to stream 9 as well as stream8 is EOL
=> [release-ocm-2.9] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

src/installer/installer.go, src/installer/installer_test.go
As described by the analysis in https://issues.redhat.com/browse/OCPBUGS-41811, in some cases the bootstrap node may reboot before the workers started the joining process, thus removing the assisted-service that it's still required by the workers. This prevents the worker to successfully join the cluster, causing the failure of the cluster deployment.
This patch introduces an explicit synchronization between the bootstrap node and the workers (only in case the installation was performed via the agent-based installer), delaying the bootstrap reboot until all the workers passed the `waiting for control plane` stage.
=> OCPBUGS-41811: (agent-based installer) let the bootstrap wait for workers before the reboot

go.mod, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/assisted_installer_controller/mock_controller.go, src/common/common.go, src/common/common_test.go, src/installer/installer.go, src/main/assisted-installer-controller/assisted_installer_main.go
is unavailable in agent-based installs.
assisted-service runs on the bootstrap node in agent-based installs. The bootstrap node reboots after the control plane is available.
If the assisted-installer-controller restarts after the bootstrap node reboots, or for some reason the controller is never able to contact assisted-service, the controller loops waiting or assisted-service to become available, times out, and exits.
With compact clusters, because the controller exited and is unable to approve CSRs, the third control plane node is unable to join the cluster causing the cluster installation to fail.
If the invoker is agent-installer, instead of exiting, this patch allows the controller to continue to run when assisted-service is offline.
Because assisted-service may be unavailable, …
=> OCPBUGS-38466: Allow controller to continue when assisted-service

Dockerfile.assisted-installer-build
Same as https://github.com/openshift/assisted-service/pull/6902
=> NO-ISSUE: Pin gocov version

Dockerfile.assisted-installer-build, src/assisted_installer_controller/mock_controller.go, src/assisted_installer_controller/mock_reboots_notifier.go, src/ignition/mock_ignition.go, src/inventory_client/mock_inventory_client.go, src/k8s_client/mock_k8s_client.go, src/ops/execute/mock_execute.go, src/ops/mock_ops.go
The change to use `go.uber.org/mock` instead of the deprecated `github.com/golang/mock` was was mostly done in the past. But the _Dockerfile_ wasn't updated to use the new `mockgen` command.  As a result if one installs the `mockgen` with the command from the dockerfile and then runs `make generate` the resulting code doesn't build:
```
$ grep mockgen Dockerfile.assisted-installer-build
go install github.com/golang/mock/mockgen@v1.6.0 && \
$ go install github.com/golang/mock/mockgen@v1.6.0
$ make generate
go generate ..
make format
make[1]: Entering directory '/files/projects/assisted-installer/repository'
make[1]: Leaving directory '/files/projects/assisted-installer/repository'
$ make build
CGO_ENABLED=0  go build -o build/installer src/main/main.go …
```
=> NO-ISSUE: Update Dockerfile to use `go.uber.org/mock`

src/assisted_installer_controller/assisted_installer_controller.go, src/ops/ops.go, src/ops/ops_test.go
There seems to be an issue with ostree command could not run successful zipl command on s390x architecture. For the time being the reason is unknown (it could be that the /boot directory is not mounted with rw option).
Until the root cause is not found the overwrite of the image for s390x will be skipped by checking the uname before overwrite happen.
This patch adds a uname check to the OverwriteOsImage function. Beside that the ops_test will be adapted accordingly.
The fix was tested against integration envrionment:
[root@a3e06001 ~]# oc get no
NAME                                 STATUS   ROLES                         AGE     VERSION …
=> OCPBUGS-42553: Rhcos fails to reboot for skip mco reboot on s390x

Dockerfile.assisted-installer-controller-mce, Dockerfile.assisted-installer-mce
As part of migrating to konflux, we need to update our downstream dockerfiles for mce and put them in our upstream repos.
Part-of [MGMT-19371](https://issues.redhat.com//browse/MGMT-19371)
=> MGMT-19371: Add downstream dockerfiles for mce

src/ops/ops.go
There is a race condition between the mount and setting the boot order, this pr adds a retry to the mount operation.
=> OCPBUGS-45116: Add retry to mount efi device

.tekton/assisted-installer-controller-mce-downstream-main-pull-request.yaml, .tekton/assisted-installer-controller-mce-downstream-main-push.yaml, .tekton/assisted-installer-mce-downstream-main-pull-request.yaml, .tekton/assisted-installer-mce-downstream-main-push.yaml
Update the tekton pipelines used to build mce downstream images to be multi-arch.
Part-of [MGMT-19390](https://issues.redhat.com//browse/MGMT-19390)
=> MGMT-19390: Update mce's tekton pipelines to be multi-arch

.tekton/assisted-installer-downstream-main-pull-request.yaml, .tekton/assisted-installer-downstream-main-push.yaml
Configure konflux builds for downstream images of assisted-installer to be multi-arch and fix references to incorrect task.
Part-of [MGMT-19474](https://issues.redhat.com//browse/MGMT-19474)
=> MGMT-19474: Configure multi-arch konflux builds for downstream images for assisted-installer

.tekton/assisted-installer-controller-downstream-main-pull-request.yaml, .tekton/assisted-installer-controller-downstream-main-push.yaml
Configure konflux builds for downstream images of assisted-installer-controller to be multi-arch and fix references to incorrect task.
Part-of [MGMT-19474](https://issues.redhat.com//browse/MGMT-19474)
=> MGMT-19474: Configure multi-arch konflux builds for downstream images for assisted-installer-controller

.tekton/assisted-installer-controller-downstream-main-pull-request.yaml, .tekton/assisted-installer-controller-downstream-main-push.yaml, .tekton/assisted-installer-controller-mce-downstream-2-13-pull-request.yaml, .tekton/assisted-installer-controller-mce-downstream-2-13-push.yaml, .tekton/assisted-installer-controller-mce-downstream-main-pull-request.yaml, .tekton/assisted-installer-controller-mce-downstream-main-push.yaml, .tekton/assisted-installer-downstream-main-pull-request.yaml, .tekton/assisted-installer-downstream-main-push.yaml, .tekton/assisted-installer-mce-downstream-2-13-pull-request.yaml, .tekton/assisted-installer-mce-downstream-2-13-push.yaml, .tekton/assisted-installer-mce-downstream-main-pull-request.yaml, .tekton/assisted-installer-mce-downstream-main-push.yaml
A lot of time our pipelines as well as other teams' pipelines are stuck because they are unable to provision hosts with different architectures to build the images.
Because we currently don't use the multi-arch images we build with konflux, we will stop building multi-arch for now and readd those architectures when we need them.
Part-of [MGMT-19507](https://issues.redhat.com//browse/MGMT-19507)
=> MGMT-19507: Stop using multi-arch builds in konflux

go.mod, go.sum, vendor/modules.txt
Update github.com/gin-gonic/gin package version to v1.9.1 for usage in indirect dependencies.
=> NO-ISSUE: update gin version

.tekton/assisted-installer-controller-downstream-main-push.yaml, .tekton/assisted-installer-downstream-main-push.yaml
Our integration environment uses latest tags, so we need the push-event pipelines to also push latest tag.
Part-of [MGMT-19595](https://issues.redhat.com//browse/MGMT-19595)
=> MGMT-19595: Push latest tag for downstream images after merge to konflux int repo

Dockerfile.assisted-installer-controller-downstream, Dockerfile.assisted-installer-controller-mce, Dockerfile.assisted-installer-downstream, Dockerfile.assisted-installer-mce
Currently our base images use ubi9 and MintMaker wants to upgrade it to 9.5, because MintMaker looks at the repo and tries to upgrade to the newest tag.
This changes the base image to use a repo that is just for rhel9.4.
Part-of [MGMT-19381](https://issues.redhat.com//browse/MGMT-19381)
=> MGMT-19381: Change downstream base images to rhel9.4 instead of ubi9

.tekton/assisted-installer-controller-downstream-main-pull-request.yaml, .tekton/assisted-installer-controller-downstream-main-push.yaml, .tekton/assisted-installer-downstream-main-pull-request.yaml, .tekton/assisted-installer-downstream-main-push.yaml
Currently downstream images are only built for x64, but we need to build for arm, s390x and ppc64le as well.
These downstream images are going to be used by SaaS.
=> NO-ISSUE: Make konflux builds for downstream images to be multi-arch

.tekton/assisted-installer-controller-downstream-main-pull-request.yaml, .tekton/assisted-installer-controller-downstream-main-push.yaml, .tekton/assisted-installer-controller-mce-downstream-2-13-pull-request.yaml, .tekton/assisted-installer-controller-mce-downstream-2-13-push.yaml, .tekton/assisted-installer-controller-mce-downstream-main-pull-request.yaml, .tekton/assisted-installer-controller-mce-downstream-main-push.yaml, .tekton/assisted-installer-downstream-main-pull-request.yaml, .tekton/assisted-installer-downstream-main-push.yaml, .tekton/assisted-installer-mce-downstream-2-13-pull-request.yaml, .tekton/assisted-installer-mce-downstream-2-13-push.yaml, .tekton/assisted-installer-mce-downstream-main-pull-request.yaml, .tekton/assisted-installer-mce-downstream-main-push.yaml
In our konflux build pipelines, there is a task to check snyk to warn us on potential code vulnerabilities.
However there are some issues it find that we don't care about, so we need to add the problematic files as a list for snyk to ignore.
Part-of [MGMT-19748](https://issues.redhat.com//browse/MGMT-19748)
=> MGMT-19748: Configure snyk ignore

.tekton/assisted-installer-controller-downstream-main-pull-request.yaml, .tekton/assisted-installer-controller-downstream-main-push.yaml, .tekton/assisted-installer-controller-mce-downstream-2-13-pull-request.yaml, .tekton/assisted-installer-controller-mce-downstream-2-13-push.yaml, .tekton/assisted-installer-controller-mce-downstream-main-pull-request.yaml, .tekton/assisted-installer-controller-mce-downstream-main-push.yaml, .tekton/assisted-installer-downstream-main-pull-request.yaml, .tekton/assisted-installer-downstream-main-push.yaml, .tekton/assisted-installer-mce-downstream-2-13-pull-request.yaml, .tekton/assisted-installer-mce-downstream-2-13-push.yaml, .tekton/assisted-installer-mce-downstream-main-pull-request.yaml, .tekton/assisted-installer-mce-downstream-main-push.yaml
The current buildah images in the tekton pipelines accidentally create the SBOM with CycloneDX 1.6 which causes a violation in the ECP check.
These new images set the CycloneDX to 1.5 as the ECP check expects.
=> NO-ISSUE: Update buildah image to fix a bug with SBOM

src/config/config.go, src/config/config_test.go, src/installer/installer.go, src/installer/installer_test.go, src/ops/mock_ops.go, src/ops/ops.go, src/ops/ops_test.go
This indicates the container image that should be installed and booted for the installed host. It also indicates that we should install to the currently booted disk, in a new stateroot, rather than expecting a device path.
https://issues.redhat.com/browse/MGMT-19100
cc @tsorya @rccrdpccl @eranco74
=> MGMT-19100: Install to the current boot device when CoreosImage is set

src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/assisted_installer_controller/operator_handler.go, src/inventory_client/inventory_client.go, src/inventory_client/mock_inventory_client.go, src/main/assisted-installer-controller/assisted_installer_main.go
The purpose of this PR is to resolve a bug caused by a race condition between the main thread
of assisted installer controller and a goroutine responsible for monitoring the status of 
OLM operators.
When the main thread reaches the stage where cluster installation has been deemed complete it 
will cancel the contexts of any Go routines it spawned, including the OLM operator monitor. 
We use cache upon the status of monitored OLM operators and this is relevant to this bug.
Upon shutdown, this monitor thread performs final checks of the installed operators, this final
check depends on a cached result, which, coupled with a bug that causes the operator installation status to
be inconsistent with cache content, leads to a scenario where the installer will report a complete installation
while …
=> MGMT-19621: Fix Race condition between the OLM operators monitor to the cluster installation monitor

src/installer/installer.go, src/installer/installer_test.go, src/ops/mock_ops.go, src/ops/ops.go, src/ops/ops_test.go
This PR adds support to the existing rootfs install strategy for some of the `coreos-installer` args that we allow users to specify.
Specifically `--append-karg`, `--remove-karg`, and `--copy-network`.
For the karg ones, the corresponding arg is added to the ostree command args which handles editing the boot loader configs.
For the copy network, the network manager keyfiles  are copied into `/boot/coreos-firstboot-network` which is the same thing `coreos-installer` does when provided `--copy-network`
Resolves https://issues.redhat.com/browse/MGMT-19101
=> MGMT-19101: Respect installer args

Dockerfile.assisted-installer, Dockerfile.assisted-installer-controller
Currently, in most of assisted installer components CI images we don't have a way to tell from which commit reference the image was built. Since We use an image stream for each component, and we import these streams from one CI component configuration to another, we might end up with images to are not up-to-date. In this case, we would like to have the ability to check if this is actually the case.
=> MGMT-19819: Add the commit reference from which the image is built to the image

.tekton/assisted-installer-acm-ds-2-14-pull-request.yaml, .tekton/assisted-installer-acm-ds-2-14-push.yaml, .tekton/assisted-installer-controller-acm-ds-2-14-pull-request.yaml, .tekton/assisted-installer-controller-acm-ds-2-14-push.yaml
Now downstream images are built with Kofnflux, therefore we change the references in the master branch to ocm-2.14.
=> MGMT-19950: Modify Konflux YAMLs to ocm-2.14

deploy/assisted-installer-controller/assisted-installer-controller-cm.yaml.template, deploy/assisted-installer-controller/assisted-installer-controller-pod.yaml.template, src/assisted_installer_controller/assisted_installer_controller.go, src/assisted_installer_controller/assisted_installer_controller_test.go, src/config/config.go, src/config/config_test.go, src/installer/installer.go, src/installer/installer_test.go, src/main/assisted-installer-controller/assisted_installer_main.go, src/ops/ops.go
phase 1 of replacing the refference HighAvailabilityMode with ControlPlaneCount
in the first stage it still accepst --high-availability-mode as a command line argument, but it is being converted to ControlPlaneCount in the following maner:
- ControlPlaneCount is being set to 3 if --high-availability-mode is set to full
- ControlPlaneCount is being set ot 1 if --high-availability-mode is set to none
After the phase 1 of assisted-installer-agent is being merged --high-availability-mode will be fully removed from the valid parameters.
=> MGMT-19421: phase 1 of replacing the refference HighAvailabilityMode with ControlPlaneCount

Dockerfile.assisted-installer
Currently, in most of assisted installer components CI images we don't have a way to tell from which commit reference the image was built. Since We use an image stream for each component, and we import these streams from one CI component configuration to another, we might end up with images to are not up-to-date. In this case, we would like to have the ability to check if this is actually the case.
=> [release-ocm-2.11] MGMT-19819: Add the commit reference from which the image is built to the image

Dockerfile.assisted-installer
Currently, in most of assisted installer components CI images we don't have a way to tell from which commit reference the image was built. Since We use an image stream for each component, and we import these streams from one CI component configuration to another, we might end up with images to are not up-to-date. In this case, we would like to have the ability to check if this is actually the case.
=> [release-ocm-2.10] MGMT-19819: Add the commit reference from which the image is built to the image

Dockerfile.assisted-installer
Currently, in most of assisted installer components CI images we don't have a way to tell from which commit reference the image was built. Since We use an image stream for each component, and we import these streams from one CI component configuration to another, we might end up with images to are not up-to-date. In this case, we would like to have the ability to check if this is actually the case.
=> [release-ocm-2.9] MGMT-19819: Add the commit reference from which the image is built to the image

src/config/config.go
[MGMT-19421](https://issues.redhat.com//browse/MGMT-19421): remove all references of HighAvailabilityMode and the command line argument --high-availability-mode
=> MGMT-19421: remove all references of HighAvailabilityMode and the command line argument --high-availability-mode

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
Upgrading to github.com/golang-jwt/jwt/v4 v4.5.2.
Commands Run : 
go get github.com/golang-jwt/jwt/v4
go mod tidy && go mod vendor
=> OCPBUGS-53720: Bump jwt to 4.5.2

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
Bump `github.com/golang-jwt/jwt/v4` to `v4.5.2` to fix `CVE-2025-30204` http://issues.redhat.com/browse/ACM-19179 http://issues.redhat.com/browse/ACM-19184 http://issues.redhat.com/browse/ACM-19174
=> [release-ocm-2.11]-ACM-19179: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
Bump `github.com/golang-jwt/jwt/v4` to `v4.5.2` to fix `CVE-2025-30204` http://issues.redhat.com/browse/ACM-19175 http://issues.redhat.com/browse/ACM-19185 http://issues.redhat.com/browse/ACM-19180
=> [release-ocm-2.12]-ACM-19175: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
Bump `github.com/golang-jwt/jwt/v4` to `v4.5.2` to fix `CVE-2025-30204` http://issues.redhat.com/browse/ACM-19178 http://issues.redhat.com/browse/ACM-19173 http://issues.redhat.com/browse/ACM-19183
=> [release-ocm-2.13]-ACM-19178: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2

src/installer/installer.go, src/installer/installer_test.go, src/k8s_client/k8s_client.go, src/k8s_client/mock_k8s_client.go, src/main/drymock/dry_mode_k8s_mock.go
Currently the assisted-installer running on the bootstrap waits for 2 control plane nodes to be ready, but with TNA it's possible that there will only be 1 control plane node (without the bootstrap).
On clusters like that we need to wait for only 1 control plane node to be ready, and then wait for at least 1 arbiter node to be ready.
Closes [MGMT-20479](https://issues.redhat.com//browse/MGMT-20479)
=> MGMT-20479: Update assisted-installer to allow TNA Clusters

go.mod, src/installer/installer.go, src/installer/installer_test.go
Originally, GetControlPlaneReplicas and GetArbiterReplicas were called once outside a retry. These functions can fail since they call the spoke cluster's kube api server, which most likely is not ready by the time the installer is checking for these Nodes. This leads to the cluster prematurely failing because of the error returned from these functions.
This moves the functions into the retry block that waitForNodes already uses so that the whole install doesn't fail when the spoke's kube apiserver is not ready yet.
---
Failures encountered in slack thread: https://redhat-internal.slack.com/archives/C014N2VLTQE/p1745997401995939
Original code added here https://github.com/openshift/assisted-installer/commit/c43bcb972dc310561de5649370e71172311ae090#diff-1046cc2d18cf5f82336bbad36a2d28540606e1 …
=> MGMT-20534: Move getting Node replicas into waitForNodes

src/ops/ops.go, src/ops/ops_test.go
Currently assisted-service generates `HTTP` endpoints for MCO pointer ignitions in day2, compared to `HTTPS` for day1. Assisted Installer expects an `HTTPS` endpoint and CA certificate, therefore day2 hosts fail skipping `MCO` reboot, and  delays the installation by 20 minutes.
logs:
```
May 05 12:42:11 localhost.localdomain installer[2721]: time="2025-05-05T12:42:11Z" level=info msg="Updating node installation stage: Waiting for control plane - " request_id=48bfbb1b-eaed-41bf-a2be-db5a6561aca9
May 05 12:42:11 localhost.localdomain installer[2721]: time="2025-05-05T12:42:11Z" level=warning msg="failed to get encapsulated Machine Config" error="CA cert is empty"
May 05 12:42:16 localhost.localdomain installer[2721]: time="2025-05-05T12:42:16Z" level=warning msg="failed to get encapsulated …
```
=> MGMT-20567: Enable HTTP endpoint for MCO ignition

src/ops/ops.go, src/ops/ops_test.go
`cp` complains for a glob path if no files exist in the source directory. This causes the whole install to fail when static networking is present, but no config matched for a particular host.
`rsync` doesn't complain in the same way and allows the command to be run unconditionally.
Specifically, before this fix, installs would fail with the following logs if we had the copy network flag, but no files in the source directory:
```
Feb 14 22:04:52 localhost.localdomain installer[3170]: time="2025-02-14T22:04:52Z" level=info msg="copying network files from /etc/NetworkManager/system-connections to /boot/coreos-firstboot-network"
Feb 14 22:04:52 localhost.localdomain assisted-installer[3168]: time="2025-02-14T22:04:52Z" level=info msg="copying network files from …
```
=> MGMT-19973: Use rsync over cp to set up networking files for first boot

src/assisted_installer_controller/operator_handler.go
In this PR, we improve the logging by adding the operator's availability status alongside its name. This way, the logs will not only show that we are checking the operator's status, but also what the actual result is. This makes the logs more informative and helps us better understand the outcome of the availability check without having to look at additional data.
=> MGMT-11622: operator status should be logged

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/github.com/golang/glog/internal/logsink/logsink.go, vendor/modules.txt
=> OCPBUGS-58649: Bump github.com/golang/glog to 1.2.4

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/github.com/golang/glog/internal/logsink/logsink.go, vendor/modules.txt
=> OCPBUGS-58646: Bump github.com/golang/glog pkg version to 1.2.4

src/ops/ops.go, src/ops/ops_test.go
Assisted installer used naive string concatenation for partition finding, causing failures with device mapper devices (dm-*). For example, trying to mount `/dev/dm-02` instead of the correct `/dev/dm-2`.
Replace string concatenation with robust `lsblk --json` based partition discovery that works with all device types:
- Device mapper: `/dev/dm-0` → `/dev/dm-2`, `/dev/dm-3`, `/dev/dm-4`
- Standard SATA: `/dev/sda` → `/dev/sda2`, `/dev/sda3`, `/dev/sda4`  
- NVMe: `/dev/nvme0n1` → `/dev/nvme0n1p2`, `/dev/nvme0n1p3`, `/dev/nvme0n1p4`
- MMC: `/dev/mmcblk1` → `/dev/mmcblk1P2`, `/dev/mmcblk1P3`, `/dev/mmcblk1P4`
- Add `getPartitionPathFromLsblk()` function using `lsblk --json` output parsing
- Update `OverwriteOsImage()` to use new partition discovery method
- Fix `calculateFreePercent()` to …
=> [master] MGMT-20756: assisted installer naive string concatenation for partition finding

Dockerfile.assisted-installer, Dockerfile.assisted-installer-build, Dockerfile.assisted-installer-controller, Dockerfile.assisted-installer-controller-downstream, Dockerfile.assisted-installer-controller-mce, Dockerfile.assisted-installer-downstream, Dockerfile.assisted-installer-mce, src/ops/ops_test.go
This commit updates the assisted-installer project to use Go 1.24 and fixes compatibility issues that arose from the Go version update.
Context:
• This PR resolves the failed Renovate PR attempt that automatically tried to update to Go 1.24 
• The automated update failed due to unit test failures caused by TLS certificate validation changes 
• Manual intervention was required to fix the test compatibility issues before the Go version update
What was changed:
• Updated Dockerfiles (excluding OCP-specific ones) to use Go 1.24 toolset instead of Go 1.21 
• Modified unit tests in src/ops/ops_test.go to handle TLS certificate validation changes
Why these changes were needed:
• Go 1.24 introduced stricter TLS security defaults and certificate validation 
• The previous test approach used static …
=> MGMT-21454: update Go to 1.24 and adapt unit-tests

Dockerfile.assisted-installer-downstream
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
=> KONFLUX-6210: fix and set name and cpe label for assisted-installer-ds-main
